### ISSUE TITLE
MsSqlBuilder.ConstructFullInsertStatement does not respect databaseColumnName in output clause.

### ISSUE THREAD

**Issue by NikGovorov** [MoonStorm/Dapper.FastCRUD#10]

**Comment by NikGovorov** [comment]
@MoonStorm, please let me know if you would like me to create PR for the issues, fixes are trivial and had to fork anyway.

**Comment by MoonStorm** [comment]
Of course. Just make sure you target the BETA branch.

**Comment by MoonStorm** [comment]
I've extended the support for database column names, however I don't endorse using them for data layer entities. The changes are part of 2.1 release, which I just published on NuGet. Let me know if they solve your problem.

Added to the FAQ section.

**Comment by NikGovorov** [comment]
I believe every identifier used in a database query should be wrapped with  ```tableAndColumnDelimiter```.

**Comment by MoonStorm** [comment]
Yep. I missed that one. Thanks.

**Comment by MoonStorm** [comment]
Fixed in 2.2 BETA.
