### ISSUE TITLE
No Models folder with dotnet core 2.0 templates

### ISSUE THREAD

**Issue by NotAClue** [MoonStorm/Dapper.FastCRUD#100]
When installing the "Dapper.FastCrud.ModelGenerator" no Models folder is created and there are no tt files added to the project.

I believe this is an issue with the project templates as dependencies are not installed with them either.

Steve

**Comment by MoonStorm** [comment]
It's a problem with NuGet being a pos when it comes to supporting all the features the old one did when it comes to this type of projects. Half ass job as usual when it comes to M$.

**Comment by MoonStorm** [comment]
I'll tinker a bit with the package to see if I can get it to play nice. I do have to migrate off MyGet first,

**Comment by MoonStorm** [comment]
So far I couldn't find a way to deploy T4 templates in .NET standard projects.

**Comment by Omzig** [comment]
In .net Core 2.1 also does not get any TT or model folder created...
