### ISSUE TITLE
Multiple Includes, incorrect syntax near...

### ISSUE THREAD

**Issue by Nuklon** [MoonStorm/Dapper.FastCRUD#105]
Such as this:

`conn.Find<Main>(x => x.Include<Second>().Include<Third>());`

Main has a reference (fk, int) to Second and Third.
Third only has a reference (fk, int) to Second.

This throws an exception, incorrect syntax near Second.

Is there any way I can get this to work correctly? I've tried several combinations but it always ends up with an exception one way or another.

(thanks for this helper, it's working really well with the rest).

**Comment by Nuklon** [comment]
I've been going through the code, @MoonStorm, and I think this fixes this issue. In the SqlStatementBuilder, this needs to be added:

 `  if (joinClauseBuilder.Length > 0)
                        {
                            joinClauseBuilder.Append(" AND ");
                        }
`
Before 
`joinClauseBuilder.Append('(');
                        for (var firstEntityPropertyIndex = 0; firstEntityPropertyIndex<firstEntityPropertyMappings.Length; firstEntityPropertyIndex++)`
https://github.com/MoonStorm/Dapper.FastCRUD/blob/master/Dapper.FastCrud/SqlBuilders/StatementSqlBuilder.cs#L483

Otherwise it generates code like this (which is obviously incorrect):
LEFT OUTER JOIN [Second] ON ([First].[SecondId]=[Second].[Id])([Third].[SecondId]=[Second].[Id]) 

All memory db tests still run OK, haven't found any issues with it either, but I'm not that familiar with the code.

**Comment by MoonStorm** [comment]
Thanks for looking into it. Could you create a new test for this particular case and post a PR with the fix and the test?

**Comment by BerkCalik** [comment]
Is there an update on that?

**Comment by mehdishokr** [comment]
Unfortunately I have to leave FastCrud. because reported bug have not been established after 6 months

**Comment by generik0** [comment]
Remember, this is open source. The best way to fix a bug is to contribute

**Comment by MoonStorm** [comment]
We have re-coded the entire relationship logic for 3.0. If your scenario is still a problem, please reopen this issue.
