### ISSUE TITLE
GetSqlBuilder<T>.Format with multiple types

### ISSUE THREAD

**Issue by FruitAndAShape** [MoonStorm/Dapper.FastCRUD#107]
I'm building an update query that contains a subquery from a different table to the one being updated.  `GetSqlBuilder<T>.Format` will only let me refer to the table and columns of its type T. How can I include multiple types in the string without breaking the string into several formatted parts?

**Comment by Freydoonk** [comment]
You can use `Sql.Table<T>` and `Sql.Column<T>` methods to generate your query. Like bellow:
```

var rawSqlQuery = OrmConfiguration.GetSqlBuilder<User>().Format(
        $@" SELECT {Sql.Column<Person>(nameof(Person.FirstName))},
                   {nameof(User.Username):C}
            FROM
                   {Sql.Table(Person)} INNER JOIN {nameof(User):T} ON
                       {nameof(User.PersonID):C} = {Sql.Column<Person>(nameof(Person.ID))} ");
```

The `Sql` class contains more helpful methods.

**Comment by FruitAndAShape** [comment]
Great, thanks.
