### ISSUE TITLE
PostgreSqlBuilder should use " as tableAndColumnDelimiter.

### ISSUE THREAD

**Issue by NikGovorov** [MoonStorm/Dapper.FastCRUD#11]

**Comment by MoonStorm** [comment]
I made the change in the ``PostgreSqlBuilder``, but soon after I realized how rubbish PostgreSql starts behaving. People will be forced to start using delimiters in the SQL as well, whether they like it or not:
``where ""{nameof(Entity.Property)}"" = 'Alice'`` or 
``where {sqlBuilder.GetColumnName(nameof(Entity.Property)} = 'Alice'``
Otherwise the names won't be properly resolved. 

So for the time being I've reverted my changes. In the future, I will make this a choice. 

Added to the FAQ section.

**Comment by NikGovorov** [comment]
We could wrap all arguments of ```FormattableString``` that are entity properties names with ```tableAndColumnDelimiter```(and transform them to ```databseColumnName``` if configured). 

Currently we use it like that: ```$"where [{nameof(Entity.Property)}] = 'Alice'".ToAnsiQuotedIdentifiers()```, ```ToAnsiQuotedIdentifiers``` is simple string extension method that replaces '[' and ']' with '"', it works on both sql server and postgres.

Thoughts?

**Comment by MoonStorm** [comment]
That is a wonderful idea. The ``FormattableString`` gives us access to both the format and the arguments. 

Problems will arise however when referencing other tables in clauses:
``$where {nameof(Person.EmployeeId)} in (select {nameof(Employee.Id)} from {nameof(Employee)}))``. How are we gonna handle that?

**Comment by MoonStorm** [comment]
Following your idea, another approach that avoids false positives and gives more control to the developers would be using a custom formatter in the library:
``$where {nameof(Person.EmployeeId):C} = 'Alice'``
The final sql would use something like ``formattableQuery.ToString(new SqlFormatProvider())``
The ``SqlFormatProvider`` will provide a formatter that looks for a ``C`` specifier for columns in the context of the current entity.

Still doesn't solve referencing other entities/tables. Or it could, but in the format people will need to provide the name of the referencing entity in a ``T`` specifier.

**Comment by NikGovorov** [comment]
Good point, to avoid ambiguity in such cases I think it's reasonable to use another C# 6 feature 'Using static members':
```$where {nameof(Person.EmployeeId)} in (select {Table<Employee>(nameof(Employee.Id))} from {Table<Employee>()}))```

It will also allow to use expressions:
```$where {nameof(Person.EmployeeId)} in (select {Table<Employee>(e => e.Id)} from {Table<Employee>()}))```.

**Comment by MoonStorm** [comment]
Looks good. Will definitely go into the next release, one way or another. It does need slight refactoring of the sql builder.

**Comment by MoonStorm** [comment]
Released in 2.2 BETA
