### ISSUE TITLE
[ModelsGenerator] Foreign key to same table and IncludeRelationships

### ISSUE THREAD

**Issue by kipusoep** [MoonStorm/Dapper.FastCRUD#112]
If you have a table with some sort of parent/child construction and thus having a foreign key to itself, and when you've got IncludeRelationships set to true, the navigational property gets the same name as the class it's contained in.
For C# this will give you a compilation error.

**Comment by alpersilistre** [comment]
Can you find any solution to this problem? I am having the same issue after IncludeRelationships set to true.

**Comment by MoonStorm** [comment]
We had to rewrite the entire code for relationships to allow for a scenario like this, but it's now supported in 3.0. We'll update the wiki soon.
