### ISSUE TITLE
Only 7 entities are allowed in a relationship

### ISSUE THREAD

**Issue by kipusoep** [MoonStorm/Dapper.FastCRUD#113]
> Only 7 entities are allowed in a relationship 
 
Why?
https://github.com/MoonStorm/Dapper.FastCRUD/blob/537456887c0d9cf35dfed8efccf938b0acbd5ccf/Dapper.FastCrud/SqlStatements/SevenEntitiesRelationshipSqlStatements.cs#L36

**Comment by MoonStorm** [comment]
This is how many Dapper supports in a relationship.
