### ISSUE TITLE
One To One same table

### ISSUE THREAD

**Issue by adrianocavalari** [MoonStorm/Dapper.FastCRUD#118]
Hi guys,

I'm having a problem to fill up the object, example:

`   [Table("person")]
    public class Person : ICloneable
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity), Column("id")]
        public Guid Id { get; set; }

        [ForeignKey(nameof(Manager)),Column("manager_id")]
        public Guid? ManagerId { get; set; }
        public Person Manager { get; set; }
   }`

The manager return null, I tried to use include statement, but it returns error: `table name "person" specified more than once`

Do anyone have some solution for that?

Thanks.

**Comment by MoonStorm** [comment]
Yeah, this is a problem. This is not currently supported.

**Comment by MoonStorm** [comment]
It is now supported in 3.0. The wiki holds information about usage.
