### ISSUE TITLE
Get the query generated

### ISSUE THREAD

**Issue by adrianocavalari** [MoonStorm/Dapper.FastCRUD#119]
Hi Guys,

Is there any way to get the query that was generated?

Thanks.

**Comment by antonis-sna** [comment]
Go to Dapper.FastCrud source and find your builder under SqlBuilders. For example, if you use MSSQL Server go to SqlBuilders -> **MsSqlBuilder**.cs and in **ConstructFullSelectStatementInternal**() method you will find your **Select** statement. There you can paste something like :
```
#if DEBUG
   Debug.Write(sql);
#endif
```
so you can see your query in the output window

**Comment by adrianocavalari** [comment]
Great, Thanks @antonis-sna
