### ISSUE TITLE
Entityframework code first entities

### ISSUE THREAD

**Issue by moxplod** [MoonStorm/Dapper.FastCRUD#12]
Hi - I have a project with entity framework code first entities, generated from an existing database by reverse engineering a model, want to start using the same entities to use a few queries to go through FastCrud. Not sure if you have tried that.

What changes do you think i would need to make to the entities, to make it work with both?
Would the navigational properties (the public virtual ICollection properties for foreign keys) cause any issues with fastcrud?

**Comment by MoonStorm** [comment]
Those properties shouldn't cause problems. I'm only looking for properties with simple types. If that's not the case, let me know.

For code first entities you're gonna have to register their special properties at runtime prior to usage. The wiki contains a section describing how this is done.

I am working on a new version where a property named ``Id`` will be registered automatically as a primary key +  db generated, but only if the entity has no orm specific attributes. For these simple entities, registration won't be necessary any more.
In the same version I'm going to expose a way to very easy override the conventions the library is using by default.

**Comment by MoonStorm** [comment]
Library convention rules are now being exposed and can be easily changed. Please check the updated docs for more info.

**Comment by MoonStorm** [comment]
Support for the ``MetadataType`` attribute was added in the latest BETA version. Docs updated with more info.
