### ISSUE TITLE
Joins/Relationships don't appear to work correctly

### ISSUE THREAD

**Issue by replaysMike** [MoonStorm/Dapper.FastCRUD#122]
I'm hoping not to have to jump ship and rely on EFCore, but joins don't appear to work correctly (and as directed by the docs). Has this project been abandoned?

Small example:

```
public class Customer
{
    public Customer()
    {
        Addresses = new HashSet<Address>();
    }
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int CustomerId { get; set; }
    [ForeignKey("PrimaryAddress")]
    public int? PrimaryAddressId { get; set; }

    public virtual IEnumerable<Address> Addresses { get; set; }
    public virtual Address PrimaryAddress { get; set; }
}
```

```
public class Address
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int AddressId { get; set; }
    [ForeignKey("Customer")]
    public int CustomerId { get; set; }
    public virtual Customer Customer { get; set; }
}
```

service:

```
using (var db = new SqlConnectionManager(_options))
{
    await db.OpenAsync();
    var newcustomer = await db.Connection
        .FindAsync<Customer>(s =>
            s.Where($"{nameof(Customer.CustomerId)}=@CustomerId")
            .Include<Address>(x =>
                x.LeftOuterJoin()
            )
            .WithParameters(new { UserGlobalId = customer.UserGlobalId })
        );
    return newcustomer.FirstOrDefault();
}
```

produces the following query:

```
SELECT [Customers].[CustomerId],[Addresses].[AddressId],[Addresses].[CustomerId] 
FROM [Customers] 
LEFT OUTER JOIN [Addresses] ON ([Customers].[PrimaryAddressId]=[Addresses].[CustomerId]) 
WHERE (CustomerId=1)
```
The data has 1 customer and 2 addresses. The query returns 2 rows, however the service call returns 1 customer with no Customer.Addresses, but it does populate Customer.PrimaryAddress.

If I do the reverse, I get another problem (but easy enough to resolve).

service:

```
using (var db = new SqlConnectionManager(_options))
{
    await db.OpenAsync();
    var newaddress = await db.Connection
        .FindAsync<Address>(s =>
            s.Where($"{nameof(Address.CustomerId)}=@CustomerId")
            .Include<Customer>(x =>
                x.LeftOuterJoin()
            )
            .WithParameters(new { CustomerId = address.CustomerId })
        );
    return newaddress.ToList();
}
```

A sql error is produced, `Ambiguous column name 'CustomerId'`, which the service is using the syntax indicated on the Wiki. I can correct this by prepending the Where with a `[Addresses].{nameof(Address.CustomerId)}` specifier - indeed the sql generated is not specifying where to reference CustomerId from.

**Comment by replaysMike** [comment]
Perhaps the 2 bugs (no relationship collections are populated) and (ambiguous column reference) are related. I don't know how it determines which "AddressId" column to use in the query result, but since there are 2 columns with the same name and the `Customer.AddressId` will always equal one value, and `Addresses.AddressId` will be unique maybe there is a bug there.

**Comment by replaysMike** [comment]
After some extended debugging and head scratching I found why it doesn't work, probably to do with a logic bug on how the entities are being mapped.

Deleting the Customer.PrimaryAddressId resolves the problem. Apparently, I can't have a foreign key mapping in addition to the customer table defining a reference to the Addresses table. It would indeed be a cyclical reference, and surprisingly EF has no issue with it but would definitely cause issues on deletion without cascade.

Even though it's a perfectly acceptable situation with a nullable column, this probably wasn't incorporated into the mapping strategy.

**Comment by replaysMike** [comment]
This of course, doesn't resolve the second bug for `Ambiguous column name 'CustomerId'` issue when getting a list of addresses, but I can work around if I fully qualify the column name.

**Comment by ducman** [comment]
The first comment below fixes your ambiguous issue. The `TC` tell it to fully qualify the table name and column name in the query.

The second comment, I was just not sure if you just did a typo or not.

```sql
using (var db = new SqlConnectionManager(_options))
{
    await db.OpenAsync();
    var newcustomer = await db.Connection
        .FindAsync<Customer>(s =>
            s.Where($"{nameof(Customer.CustomerId)}=@CustomerId") // use {nameof(Custom.CustomerId):TC}
            .Include<Address>(x =>
                x.LeftOuterJoin()
            )
            .WithParameters(new { UserGlobalId = customer.UserGlobalId }) // doesn't match your where clause parameter @CustomerId
        );
    return newcustomer.FirstOrDefault();
}

**Comment by MoonStorm** [comment]
We have introduced support for aliases in 3.0, which if embraced whenever a JOINed entity gets reference, it would solve a bunch of problems.
