### ISSUE TITLE
Update Benchmarks

### ISSUE THREAD

**Issue by cocowalla** [MoonStorm/Dapper.FastCRUD#128]
The benchmarks shown in teh main readme are now 2 years out of date - it ould be create to get them updated, and also to add Entity Framework Core to the comparison.

**Comment by MoonStorm** [comment]
We finally found some time to take a look at the benchmarks and revive them! EF Core is really bad at this (we almost lost our patience waiting for them to finish), but some of the other ones have matured enough and finally caught up with ``FastCrud``!
