### ISSUE TITLE
How to use additional condition on left join?

### ISSUE THREAD

**Issue by Freydoonk** [MoonStorm/Dapper.FastCRUD#129]
I wrote this code to get all data from TableA which corresponding children records in TableB were not deleted. 
My data is:

TableA

| ID	            | Title	    |
|:-------------:|:-------------:|
|1                   |Test	           |

TableB

| ID	            | Title	    |TableAID| Deleted |  
|:----------------:|:-------------:|:-------------:|:-------------:|
| 1                      |TableB Test 1|1                  |1                   |
| 2                      |TableB Test 2|1                  |1                   |
| 3                      |TableB Test 3|1                  |1                   |

```
Connection.Find<TableA>(statement => statement
                                         .Include<TableB>(join => join.LeftOuterJoin()
                                         .Where($"{nameof(TableB.Deleted):TC} = 0")));
```
This code generate bellow SQL script:

```
SELECT 
     [TableA].[ID],
     [TableA].[Title],
     [TableB].[ID],
     [TableB].[Title],
     [TableB].[TableAID],
     [TableB].[Deleted]
FROM [TableA] LEFT OUTER JOIN 
     [TableB] ON ([TableA].[ID] = [TableB].[TableAID])
WHERE 
     ([TableB].[Deleted] = 0);
```

This query returns nothing! I need to generate bellow script so that my code works properly:
(I moved  `[TableB].[Deleted] = 0` from where clause to join statement)

```
SELECT 
     [TableA].[ID],
     [TableA].[Title],
     [TableB].[ID],
     [TableB].[Title],
     [TableB].[TableAID],
     [TableB].[Deleted]
FROM [TableA] LEFT OUTER JOIN 
     [TableB] ON ([TableA].[ID] = [TableB].[TableAID] AND [TableB].[Deleted] = 0);
```

How can I do this?

**Comment by hamidnaeemi** [comment]
Please check following one if it works for you as a workaround until extra condition feature added

`Connection.Find<TableA>(statement => statement
                                         .Include<TableB>(join => join.LeftOuterJoin()
                                         .Where($"{nameof(TableB.Deleted):TC} = 0 OR {nameof(TableB.Deleted):TC} IS NULL")));`

**Comment by Freydoonk** [comment]
> Please check following one if it works for you as a workaround until extra condition feature added
> 
> `Connection.Find<TableA>(statement => statement .Include<TableB>(join => join.LeftOuterJoin() .Where($"{nameof(TableB.Deleted):TC} = 0 OR {nameof(TableB.Deleted):TC} IS NULL")));`

It works but using  `OR statements` has performance issue and I look for a better way to do this.

**Comment by MoonStorm** [comment]
You can certainly add that condition inside the join clause like @hamidnaeemi pointed, but we will add more control on the joins soon.
