### ISSUE TITLE
vb.net

### ISSUE THREAD

**Issue by OleeOlsen** [MoonStorm/Dapper.FastCRUD#13]
Hello,

please can you tell me an example in vb.net. 

- dbConnection.Find<Entity>(
whereClause:$"{nameof(Entity.FirstName)}=@FirstNameParam",
orderClause:$"{nameof(Entity.LastName)} DESC",
skipRowsCount:10, limitRowsCount:20,
queryParameters: new {FirstNameParam: "John"});

Im new in C# and don't undertand this. Btw: This example dosen't work in Net 4.5 for me.

**Comment by VictorTomaili** [comment]
its c# 6.0 ability. 
```csharp
string.Format("{0}=@fFirstNameParam", "FirstName") 
```
equal to 
```csharp
$"{nameof(Entity.FirstName)}=@FirstNameParam"
```
second one has intellisense and refactoring advantage. 

if you are new on c# try install visual studio 2015 and use lastes version of c# and .net framework.

**Comment by OleeOlsen** [comment]
Thank you for your fast reply.  I'm sorry to say i must use Net 4.5. In your descrition you say it is possible. Please send me an example.

**Comment by VictorTomaili** [comment]
try this. its pure string way. 
```csharp
dbConnection.Find( whereClause:"FirstName=@FirstNameParam", orderClause:"LastName DESC", skipRowsCount:10, limitRowsCount:20, queryParameters: new {FirstNameParam: "John"});
```

**Comment by OleeOlsen** [comment]
Sorry it dosn't work. The compiler says "not a definition for Find with this parameter".
May be, I'm too stupid ;-)

**Comment by MoonStorm** [comment]
@OleeOlsen First of all Ole, welcome to our wonderful C# world. It's beautiful, but it's not gonna be easy for you, as I myself have realized while trying to come up with this simple VB.NET example when I have zero experience in this language.

```
Imports System.Data.SqlClient
Imports Dapper.FastCrud

Module Module1

    Sub Main()
        Using conn As New SqlConnection
            Dim persons = conn.Find(Of Person)(
                   whereClause := $"{NameOf(Person.FirstName)}=@FirstNameParam",
                   queryParameters := New With{.FirstNameParam="John"})
        End Using
    End Sub

End Module
```

I hope it makes sense. This translates to C# as follows:
```
using System.Data.SqlClient;
using Dapper.FastCrud;

namespace YourNamespace
{

    class Program
    {
        static void Main(string[] args)
        {
            using (var conn = new SqlConnection())
            {
                var persons = conn.Find<Person>(
                    whereClause: $"{nameof(Person.FirstName)}=@FirstNameParam",
                    queryParameters: new { FirstNameParam="John" });
            }
        }
    }
}
```

Both obviously assume there is a class ``Person`` defined with ``FirstName`` as a string property.

Regardless whether you want to write in VB.NET or C#, you have to use Visual Studio 2015. String interpolation is mostly a language feature, handled by the compiler, thus you can target even .NET 4.5 if you so desire.

**Comment by OleeOlsen** [comment]
@MoonStorm  Thank you for this extendet reply. You shold write a requirement-section in the wiki.
I have now installed VS 2015 and use Net 4.5. And it woks. ;-)

**Comment by MoonStorm** [comment]
You're right. I've added more on the front page. Thanks to you, now I know string interpolation was made available in VB 14 :laughing:
