### ISSUE TITLE
GetDefaultEntityMapping to get only certain columns

### ISSUE THREAD

**Issue by dquinter** [MoonStorm/Dapper.FastCRUD#131]
I'm trying to get only certain columns, but when my grid is filled, it shows all the columns. This is the code I use:

`
using (SQLiteConnection db = new SQLiteConnection(SQLiteConnectionString))
   {
      var customMapping = OrmConfiguration
         .GetDefaultEntityMapping<Product>()
         .Clone()
         .RemoveAllPropertiesExcluding(
            nameof(Producto.IDProduct),
            nameof(Producto.ProductName));
      var miLista = db.Find<Producto>(statement =>
         statement.WithEntityMappingOverride(customMapping));
      if (miLista != null)
         {
            grdDatos.DataSource = miLista.ToList();
         }
`
What I'm doing wrong?

Thanks a lot

**Comment by MoonStorm** [comment]
In this case you should create a new entity type, mapped to the same table, or manually restrict what the grid is displaying. Otherwise FastCrud is still gonna return your full entity, the only difference being that those properties you're excluding won't be filled.
