### ISSUE TITLE
InsertAsync() blocks thread?

### ISSUE THREAD

**Issue by kashelkin** [MoonStorm/Dapper.FastCRUD#132]
I write WPF application. At some point it asynchronously calls method that stores to MS SQL Server DB several instances using this code in cycle:
```
await _conn.InsertAsync(instance, statement => statement
    .AttachToTransaction(transaction));
```
During the insertion cycle interface of my application freezes.
It is not my method that blocks the thread because I can get rid of freezes calling `InsertAsync` inside of `Task.Run()`:
```
await Task.Run( () => _conn.InsertAsync(instance, statement => statement
    .AttachToTransaction(transaction)) );
```

Is InsertAsync() not quite async or I do something wrong?

Thanks in advance!

**Comment by MoonStorm** [comment]
That's usually caused by a serialization context present. Your solution with Task.Run was the right call. I did find a couple of other problems linked to the async methods which are already pushed in 2.6.
