### ISSUE TITLE
Is it possible to insert non-POCO objects?

### ISSUE THREAD

**Issue by ofir-shapira-como** [MoonStorm/Dapper.FastCRUD#136]
Consider this simplified model:

    public class School
    {
        public Manager Check { get; set; }
    }

When calling InsertAsync(school), I see null value in the database for that "complex" column, am I doing something wrong or is it not supported?

**Comment by mancku** [comment]
Hi @ofir-shapira-como  just seeing this. I'd say that you can't do that. You need to map your properties to columns, and there's no column of type _Manager_ in SQL Server

**Comment by MoonStorm** [comment]
Non POCO objects are certainly supported. See [this wiki entry](https://github.com/MoonStorm/Dapper.FastCRUD/wiki/Entity-registration) for how to achieve that.
