### ISSUE TITLE
InsertAsync is not async

### ISSUE THREAD

**Issue by FenrisWolfAtMiddleEarth** [MoonStorm/Dapper.FastCRUD#137]
In the GenericSqlStatements class there is an InsertAsync method.
Why does this method use the connection.Execute and not the connection.ExecuteAsync ?

        public async Task InsertAsync(IDbConnection connection, TEntity entity, AggregatedSqlStatementOptions<TEntity> statementOptions)
        {
            if (_sqlBuilder.RefreshOnInsertProperties.Length > 0)
            {
                var insertedEntity =
                    (await
                     connection.QueryAsync<TEntity>(
                         _sqlBuilder.ConstructFullInsertStatement(),
                         entity,
                         transaction: statementOptions.Transaction,
                         commandTimeout: (int?)statementOptions.CommandTimeout?.TotalSeconds)).FirstOrDefault();
                // copy all the database generated props back onto our entity
                this.CopyEntity(insertedEntity, entity, _sqlBuilder.RefreshOnInsertProperties);
            }
            else
            {
                connection.Execute(
                    _sqlBuilder.ConstructFullInsertStatement(),
                    entity,
                    transaction: statementOptions.Transaction,
                    commandTimeout: (int?)statementOptions.CommandTimeout?.TotalSeconds);
            }
        }

**Comment by MoonStorm** [comment]
Yeah that looks like a bug to me.

**Comment by mdx0111** [comment]
I've created the following PR to address this issue:
https://github.com/MoonStorm/Dapper.FastCRUD/pull/153

**Comment by JerryJian** [comment]
Is this library is actively maintained?

**Comment by MoonStorm** [comment]
fixed
