### ISSUE TITLE
why need to remove underline in tablename

### ISSUE THREAD

**Issue by wuzhenda** [MoonStorm/Dapper.FastCRUD#139]
I have a sql server database,many  tables  named like "by_xxx_yyy";

when using  "Dapper.FastCrud.ModelGenerator",it changed the table name from "by_xxx_yyy" to "byxxxyyy".

I read the t4 temple which  include the code below.is it OK to comment them?

`
tbl.CleanName = tbl.CleanName.Replace("_","");
tbl.ClassName=Singularize(RemoveTablePrefixes(tbl.CleanName));`

**Comment by MoonStorm** [comment]
Sorry for the late reply. The reason why we're cleaning up class names is to keep them in line with the C# naming conventions. But you are free to change that template in any way you want.
