### ISSUE TITLE
MSSQL insert issues when triggers are enabled

### ISSUE THREAD

**Issue by moxplod** [MoonStorm/Dapper.FastCRUD#14]
I am guessing the same will happen with updates and deletes.

This ORM for node js ran into the same problem with mssql which i saw upon googling. 

https://github.com/sequelize/sequelize/issues/3284

The exact error is - 
The target table 'Contact' of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause.

**Comment by moxplod** [comment]
Should we change the output clause to something like SELECT LAST_INSERT_ID()  or scope_identity.
Not sure which one is the best for MsSql server. Any ideas?

**Comment by MoonStorm** [comment]
They only work for identity column. We won't be getting the default db values like this.

**Comment by moxplod** [comment]
The other solutions are to push the values into a temp db and then return the whole row back again. Not sure if that is the most elegant.

**Comment by MoonStorm** [comment]
Yeah I was thinking the same.

```
SELECT * INTO #temp FROM Table WHERE 1=0

INSERT INTO Table() 
OUTPUT inserted.* INTO #temp
VALUES()

SELECT columns from #temp
```

I suspect the performance will drop quite a bit with this approach. 

A special case can be made for simple tables that use a numeric key having no other default columns (and most of them will be like that), in which case we can use @@IDENTITY.

**Comment by moxplod** [comment]
I am happy to create a pull request for this. Just wanted to figure out what would be the best solution.

Another thing i was thinking, though not mentioned anywhere -
Is there a way to query if the table has a trigger, then maybe do it this way with a temp table. If it does not have a trigger keep doing what is currently being done.

Not sure what will be better performance wise.

**Comment by MoonStorm** [comment]
A brilliant idea. I just tried getting the triggers for a particular table, and this works:
```
IF(EXISTS (SELECT * 
FROM sys.triggers tr 
WHERE tr.parent_id=OBJECT_ID(N'<table_name>')))
```
I suggest we embed the check into the insert statement and see its performance. If it makes a huge difference, we could change the code later and perform a one time check for triggers, as the ``MsSqlBuilder`` is unique per entity/table.

Of course I would appreciate a PR for this. 
Just make sure you get the latest code, as it just went through some serious refactoring in preparation for the next set of features. You can run the full suite of uncategorized tests on your local, which don't require external db support.

**Comment by moxplod** [comment]
Not sure why, but I am still getting the same error with the IF ELSE Statement.
The final output sql is https://gist.github.com/moxplod/14e0ec732bb4dbfa7935

**Comment by MoonStorm** [comment]
Yeah, apparently it's doing a validation check regardless of the conditions in the query, prior to using it.
Oh well, for the time being let's apply the temp table idea, regardless of the presence of the triggers. 
Here's a working example:
http://sqlfiddle.com/#!6/a818c3/15/0

**Comment by moxplod** [comment]
Cool, will look into it tomorrow. I wonder what kind of sql entity framework generates for this scenario. Or do they just reget the whole object after insert.

**Comment by MoonStorm** [comment]
Don't know but you made me curious.

**Comment by MoonStorm** [comment]
So, I've tried various things with EF6 code first, and this is the SQL it produces:

one numeric primary key:
```
exec sp_executesql N'INSERT [dbo].[Department]([Title], [Credits])
VALUES (@0, NULL)
SELECT [DepartmentID]
FROM [dbo].[Department]
WHERE @@ROWCOUNT > 0 AND [DepartmentID] = scope_identity()',N'@0 nvarchar(max) ',@0=N'Test'
```

one non-numeric primary key (in this case a default db generated guid)
```
exec sp_executesql N'DECLARE @generated_keys table([DepartmentID] uniqueidentifier)
INSERT [dbo].[Department]([Title], [Credits])
OUTPUT inserted.[DepartmentID] INTO @generated_keys
VALUES (@0, NULL)
SELECT t.[DepartmentID]
FROM @generated_keys AS g JOIN [dbo].[Department] AS t ON g.[DepartmentID] = t.[DepartmentID]
WHERE @@ROWCOUNT > 0',N'@0 nvarchar(max) ',@0=N'Test'
```

multiple primary keys
```
exec sp_executesql N'DECLARE @generated_keys table([EmployeeID] int, [AccessKey] uniqueidentifier)
INSERT [dbo].[Employee]([LastName], [FirstName], [JoiningDate])
OUTPUT inserted.[EmployeeID], inserted.[AccessKey] INTO @generated_keys
VALUES (@0, @1, @2)
SELECT t.[EmployeeID], t.[AccessKey]
FROM @generated_keys AS g JOIN [dbo].[Employee] AS t ON g.[EmployeeID] = t.[EmployeeID] AND g.[AccessKey] = t.[AccessKey]
WHERE @@ROWCOUNT > 0',N'@0 nvarchar(max) ,@1 nvarchar(max) ,@2 datetime2(7)',@0=N'First Name',@1=N'Last Name',@2='2010-01-01 00:00:00'
```

So pretty much what we thought, with the temp table, with the exception for a single numeric primary key and the table being explicitly created, which I really wouldn't want to do (as that requires a C# to SQL type conversion in our case).

I don't understand the JOIN though. What is it trying to achieve with that?

**Comment by moxplod** [comment]
That pretty much validates what we have been thinking. Thanks for digging in and getting this sql out.
With that join, maybe for some reason or corner case (with multiple keys especially - they want to get the data from the primary table and not just return the data from the inserted table).

**Comment by MoonStorm** [comment]
Yeah, but it's joining on the values from the temp table, so what's the point?
