### ISSUE TITLE
Find returning less results with included relations with pagination

### ISSUE THREAD

**Issue by KKica** [MoonStorm/Dapper.FastCRUD#149]
I am using Dapper.Fastcrud to manage my database. I have a query with included entities and with pagination as well.

It looks like this:

```
    _db.FindAsync<User>(x => x
         .Include<UserRoles>(o => o.LeftOuterJoin())
         .Include<Role>(o => o.LeftOuterJoin())
         .Where("query with params")
         .WithParameters(myParamObject)
         .OrderBy("sortByColumn")
         .Skip(0)
         .Take(10)
```
                

This query returns 5 users.

If I remove the includes, I get 10 users. It appears that Dapper converts it to something like:

 1. Do `left join`s 
 2. Do `skip&take`  
 3. Do the aggregation of roles inside user.

Because from the result there are 8 roles for 3 users and 0 roles for 2 users. (When `left join`ed, those 2 users would have a row each, and the other 3 users would have 8 rows, so 10 in total).

I have tried to put the `include` after `skip` and `take`, but without success.

Other than creating 2 different queries, what can I do? How do I fix this? 

Generated query below

```
 SELECT `user`.`id` AS `Id`,`user`.`first_name` AS `FirstName`,`user`.`last_name` AS `LastName`,`user`.`email` AS `Email`,`user_roles`.`user_id` AS `UserId`,`user_roles`.`role_id` AS `RoleId`,`role`.`id` AS `Id`,`role`.`code` AS `Code`,`role`.`name` AS `Name`
    FROM `user` 
    LEFT OUTER JOIN `user_roles` ON (`user`.`id`=`user_roles`.`user_id`) 
    LEFT OUTER JOIN `role` ON (`user_roles`.`role_id`=`role`.`id`) 
    ORDER BY `user`.`first_name` DESC 
    LIMIT 0,10
```

**Comment by MoonStorm** [comment]
Yes, this is normal. The COUNT comes straight from the db, and when the query contains JOINs, that count will come back counting the duplicates. You need to create two queries: one that doesn't include the JOINs and another one with the JOINs where the library will remove the duplicates for you and populate the child collections.

**Comment by MoonStorm** [comment]
This should work properly now in 3.0
