### ISSUE TITLE
Using Multiple Where  ... 

### ISSUE THREAD

**Issue by askarialireza** [MoonStorm/Dapper.FastCRUD#150]
Is it possible to using multi-where  clause such a :

````
return base.Count(statement => statement
		.Where($@"ISNULL({nameof(FirstMonthDueEffectiveDate.Deleted):TC},0) = 0")
		.Where($"{nameof(FirstMonthDueEffectiveDate.Id):TC} <> @Id")
		.WithParameters(new { Id = id })) > 0;
````

instead of this sample code ?

````
return base.Count(statement => statement
		.Where($@"ISNULL({nameof(FirstMonthDueEffectiveDate.Deleted):TC},0) = 0 AND {nameof(FirstMonthDueEffectiveDate.Id):TC} <> @Id")
		.WithParameters(new { Id = id })) > 0;
````

**Comment by MoonStorm** [comment]
I thought about it but it may create confusion. 
Another idea is to declare the where clause separately as an explicit FormattableString, which can be manipulated dynamically as long as it's being kept as such, then pass it to the Where method still in its FormattableString form.
