### ISSUE TITLE
Sql statement builder interfaces not taking null values

### ISSUE THREAD

**Issue by moxplod** [MoonStorm/Dapper.FastCRUD#16]
The new sql builders interfaces do not take null values. 

Not sure if i am missing anything but this will end up being very verbose if i have to check whether skip that is passed to me is NULL or not and then call the .Skip() method vs me just being able to pass the values to the old sql generator.

And so and so forth with each of the inputs - order, take, where, transaction etc.

**Comment by moxplod** [comment]
For example currently i have to put a special condition for order - which defaults to null. I will have to put similar conditions for each skip / take / etc.

public IEnumerable<T> Find(string where, object param, string order = null, int? skip = null, int? take = null)
        {
            using (var connection = DatabaseFactory.ReadOnlyConnection())
            {
                if (order == null)
                {
                    return connection.Find<T>($"{where}", null, skip, take, param);
                }
                else
                {
                    return connection.Find<T>($"{where}", $"{order}", skip, take, param);
                }
            }
        }

**Comment by MoonStorm** [comment]
Convenience versus proper validation... Would one expect  that by explicitly calling UseTransaction the method would fail when he'd passed an invalid value or not? Hmmm... :8ball: 

Up until now, those things were accepting null values because they were optional arguments. But I hate never ending lists of arguments, and I am just about to add some more.

**Comment by MoonStorm** [comment]
Ah sorry now I understand what you meant sorry. You're right.
I just pushed a build in NuGet that allows nullables.
