### ISSUE TITLE
Unable to get the first n rows or the top 1 row - IRangedConditionalResultsSqlStatementSetter

### ISSUE THREAD

**Issue by moxplod** [MoonStorm/Dapper.FastCRUD#17]
Currently if i want to get just the first row, based on any where clause. I send skip = 0 and top/limitResults = 1.
But Skip throws an exception that skip should be > 0 instead of >=0.

```
/// <summary>
        /// Skips the initial set of results.
        /// </summary>
        public TStatementOptionsBuilder Skip(long skipRecordsCount)
        {
            Requires.Argument(skipRecordsCount > 0, nameof(skipRecordsCount), "The number of records to skip must be a positive value");

            this.SkipResults = skipRecordsCount;
            return this.Builder;
        }
```

Next, if i want to get first n rows then i have to set Top( n), that it using MsSqlbuilder causes a sql exception due to the fact that it prints out a fetch n without an offset.

**Comment by MoonStorm** [comment]
Yes, that is indeed a bug. I'll add more tests and fix this today. Thanks for reporting.

**Comment by MoonStorm** [comment]
Fixed and released in BETA for both MsSql and SqLite.

**Comment by moxplod** [comment]
Thanks for fixing this so promptly! I will start using it in my project right away.

**Comment by MoonStorm** [comment]
Skip(0) shouldn't be needed any more, but 0 is now accepted as well. I've also added a validation rule for the lack of OrderBy when either Skip or Top are being used. That solves #8. MsSql complains if not there. Nobody should rely on the default db order anyway, as the optimizations in the server could change that at any moment.

**Comment by moxplod** [comment]
Yea - i ran into that as soon as i got your code - it threw up that exact validation exception. 
i think that is a good practice to force developers to specify an order by condition. instead of relying on the default order.
