### ISSUE TITLE
After Update to 2.2.0 

### ISSUE THREAD

**Issue by OleeOlsen** [MoonStorm/Dapper.FastCRUD#19]
I update to from 2.1.2.to 2.2.0. then all Extensions marked as obsolate. What's wrong?

**Comment by MoonStorm** [comment]
That's right. We wanted to add more features but we already had a long list of arguments for each of the methods.

Please check the wiki for the new style. Thanks.

**Comment by OleeOlsen** [comment]
Thanks for your reply. How about with release notes. ;-)

**Comment by MoonStorm** [comment]
Thanks for sharing your concern. I've included a warning in the release notes on NuGet.
