### ISSUE TITLE
Insert doesnt work with sqlite

### ISSUE THREAD

**Issue by SiOuz** [MoonStorm/Dapper.FastCRUD#20]
Hello,

I use your extension with sqlite.
I have an issue when the insert method is call : no such function: SCOPE_IDENTITY.

The connection : 
SQLiteConnection($"Data Source={DbFile};Version=3;");

The table is :
@"create table Fournisseur
              (
                 Id                                 INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
                 Nom                           varchar(100) not null,
                 Pays                            varchar(100) not null
              )"

Entity : 

    [Table("Fournisseur")]
    public class Fournisseur
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [ExcelColumn("Nom")] //maps the "Name" property to the "Company Title" column
        public string Nom { get; set; }
        [ExcelColumn("Pays")] //maps the "State" property to the "Providence" column
        public string Pays { get; set; }
      }

Then 
var fournisseur = new Fournisseur() { Nom = "AllInBIke", Pays = "France" };
db.Insert(fournisseur);

I have missing something ?

**Comment by SiOuz** [comment]
ok i have to set this OrmConfiguration.DefaultDialect = SqlDialect.SqLite

**Comment by MoonStorm** [comment]
That's right. Sorry for the omission. I'll update the docs.
