### ISSUE TITLE
Sqlite raise an error when we call LastInsertRowId after Insert

### ISSUE THREAD

**Issue by SiOuz** [MoonStorm/Dapper.FastCRUD#21]
I get an error when i call the LastInsertRowId from SQLiteConnection after your insert methode.
"System.InvalidOperationException: Database connection not valid for getting last insert rowid."

My code : 
public T Insert<T>(T item) where T : IPropertyId
        {
            using (var dbConnection = SimpleDbConnection())
            {
                dbConnection.Insert<T>(item);
                item.Id = dbConnection.LastInsertRowId;
                return item;
            }
        }

Do you close the connection when we call your Insert method ?

**Comment by MoonStorm** [comment]
No we don't. You'll find the value for your ``id`` inside the ``item``, if it was set up properly of course.
