### ISSUE TITLE
Update fails for entities with DatabaseGeneratedOption.Computed attribute

### ISSUE THREAD

**Issue by petsona** [MoonStorm/Dapper.FastCRUD#22]
OrmConventions.cs:
Missing call to propertyMapping.ExcludeFromInserts().ExcludeFromUpdates();  for Computed option as well, otherwise the Update, Insert commands fail. 
```C#
if (databaseGeneratedAttributes.Any(dbGenerated => dbGenerated.DatabaseGeneratedOption == DatabaseGeneratedOption.Computed))
{
     propertyMapping.SetDatabaseGenerated();
}
if (databaseGeneratedAttributes.Any(dbGenerated => dbGenerated.DatabaseGeneratedOption == DatabaseGeneratedOption.Identity))
{
      propertyMapping.SetDatabaseGenerated();
      propertyMapping.ExcludeFromInserts().ExcludeFromUpdates();
}

**Comment by MoonStorm** [comment]
A bit confusing I agree, but if you go further deeper into the code you'll realize that database generated properties are going to be ignored from inserts by default.

```
        public bool IsDatabaseGenerated
        {
            get
            {
                return (_options & PropertyMappingOptions.DatabaseGeneratedProperty) == PropertyMappingOptions.DatabaseGeneratedProperty;
            }
            set
            {
                this.ValidateState();

                if (value)
                {
                    _options |= PropertyMappingOptions.DatabaseGeneratedProperty;
                    this.IsExcludedFromInserts = true;
                }
                else
                {
                    _options &= ~PropertyMappingOptions.DatabaseGeneratedProperty;
                }
            }
        }

        public PropertyMapping SetDatabaseGenerated(bool isDatabaseGenerated = true)
        {
            this.IsDatabaseGenerated = isDatabaseGenerated;
            return this;
        }
```
You'll notice that we've got a bunch of tests having a GUID having a default value generated by the DB on INSERT but updated on UPDATE.  

At the moment, neither of the ``DatabaseGenerationOption`` enum values can be used to ignore a non-key property from an UPDATE. I suppose we should be following the [MSDN docs](https://msdn.microsoft.com/query/dev14.query?appId=Dev14IDEF1&l=EN-US&k=k(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.5);k(DevLang-csharp)&rd=true). We'll need to update the T4 template as well.

Until then, you could override the [default library conventions](https://github.com/MoonStorm/Dapper.FastCRUD/wiki/Default-library-conventions).

**Comment by yongke-bill-yu** [comment]
Hi MoonStorm, thank you for the reply.  Can you please check my code in this StackOverview question?  I am the developer having this problem:

http://stackoverflow.com/questions/34537729/databasegeneratedoption-doesnt-work-in-dapper-fastcrud

**Comment by yongke-bill-yu** [comment]
I MoonStorm.  We tried to debug locally and it turn out in "public bool IsDatabaseGenerated", there still isn't anything for update.   Here is 2 potential fix:

    public bool IsDatabaseGenerated
        {
            get
            {
                return (_options & PropertyMappingOptions.DatabaseGeneratedProperty) == PropertyMappingOptions.DatabaseGeneratedProperty;
            }
            set
            {
                this.ValidateState();

                if (value)
                {
                    _options |= PropertyMappingOptions.DatabaseGeneratedProperty;
                    this.IsExcludedFromInserts = true;
                    this.IsExcludedFromUpdates = true;  // Add This Line
                }
                else
                {
                    _options &= ~PropertyMappingOptions.DatabaseGeneratedProperty;
                }
            }
        }

        public PropertyMapping SetDatabaseGenerated(bool isDatabaseGenerated = true)
        {
            this.IsDatabaseGenerated = isDatabaseGenerated;
            return this;
        }


Alternatively, we could also fix it here:

        public virtual void ConfigureEntityPropertyMapping(PropertyMapping propertyMapping)
        {
            ... ....
            if (databaseGeneratedAttributes.Any(dbGenerated => dbGenerated.DatabaseGeneratedOption == DatabaseGeneratedOption.Computed))
            {
                propertyMapping.SetDatabaseGenerated();
                propertyMapping.ExcludeFromInserts().ExcludeFromUpdates(); // Add This Line
            }

            if (databaseGeneratedAttributes.Any(dbGenerated => dbGenerated.DatabaseGeneratedOption == DatabaseGeneratedOption.Identity))
            {
                propertyMapping.SetDatabaseGenerated();
                propertyMapping.ExcludeFromInserts().ExcludeFromUpdates();
            }
            ... ....
       }

**Comment by MoonStorm** [comment]
Got it now. The computed columns are the problem. 

Yes, that would be part of the solution. A full fix isn't as trivial as it seems though. 

1. First of all, we should probably follow the [MSDN explanation for ``DatabaseGeneratedOption``](https://msdn.microsoft.com/en-us/library/system.componentmodel.dataannotations.schema.databasegeneratedoption(v=vs.110).aspx). Problem is, I fail to understand how an identity column should be allowed in updates. Hmmm, we'll  need to check how EF deals with that attribute. Maybe ``DatabaseGeneratedOption.Identity`` doesn't mean an identity column, which is just gonna add to the confusion.
2. The update should bring the values back, same as it does for insert.
3. The T4 template needs to be updated.

**Comment by MoonStorm** [comment]
Fixed and released in 2.3.0. This version introduced breaking changes in order to align with the MSDN docs. Please check the [updated wiki](https://github.com/MoonStorm/Dapper.FastCRUD/wiki/Entity-registration) for more details.

**Comment by yongke-bill-yu** [comment]
Thank you so much for the quick fix, I will check it out next Monday ASAP.

**Comment by yongke-bill-yu** [comment]
I checked it out and it works well!  Thanks a lot!

**Comment by MoonStorm** [comment]
Glad to hear that. Let me know if you encounter any more problems. Thanks.
