### ISSUE TITLE
Column Renaming Does Not Work When Read

### ISSUE THREAD

**Issue by yongke-bill-yu** [MoonStorm/Dapper.FastCRUD#23]
Hello Again

I have a piece of code like this:

    [Table("[Report.Schedule]")]
    public partial class Report_Schedule
    {
       // ... other columns
        [Column("SCHEDULE"), Required]
        public string SCHEDULE_DETAIL { get; set; }
    }

So the column SCHEDULE would save, but the property SCHEDULE_DETAIL would never load the data from database.  If however, I change the property name back to "SCHEDULE", it would read just fine.

Here is the Column create SQL:

	[SCHEDULE] [nvarchar](max) NOT NULL,

**Comment by MoonStorm** [comment]
Could you please use the ``TableAttribute``'s ``Schema`` property for specifying the schema. e.g.
```
[Table("Schedule",Schema = "Report")]
```
If that's not an option for you, I'd suggest you override the default conventions used by the library, in particular ``GetTableName`` and ``GetSchemaName``. Check the docs for more details.

If that still doesn't fix it, could you please check the generated SQL with either the ``SQL Server Profiler`` or simply by watching the ``Events`` tab in the ``Diagnostic Tools`` window in VS2015. If you could spot the mistake, please come back to us with your findings.

**Comment by yongke-bill-yu** [comment]
Hi MoonSorm, we decided to keep the name the same for column and object mapping.  So there isn't any need to specify the column schema now.  Thanks though.

**Comment by MoonStorm** [comment]
Too bad. I really wanted to know if there was a problem with that feature. We have some tests with column names being different than the property names but maybe we missed something in a particular configuration e.g. when using schemas. 

I'd like to have more test coverage for schemas but it's been pretty neglected so far due to its minimal usage in projects.
