### ISSUE TITLE
Obsolete warning without suggestion!

### ISSUE THREAD

**Issue by fwd079** [MoonStorm/Dapper.FastCRUD#25]
Hi, I want to wrap code in a transaction. My code:

```
 using (SqlConnection con = new SqlConnection(""))
            {
                SomeEntity et = new SomeEntity();

                using (SqlTransaction trans = con.BeginTransaction())
                {
                    con.Insert(et, trans);
                }
            }

```

But I get a warning

> Severity	Code	Description	Project	File	Line	Suppression State
> Warning	CS0618	'ObsoleteDapperExtensions.Insert<TEntity>(IDbConnection, TEntity, IDbTransaction, TimeSpan?, EntityMapping<TEntity>)' is obsolete: 'Will be removed in a future version'

What is the workaround of wrapping transaction please? Because unlike Microsoft no "Use this instead" is provided?

Cheers.

**Comment by MoonStorm** [comment]
So you compare the efforts of creating and maintaining this library with Microsoft's. You reckon we've got enough manpower here to give you nice little messages...

To answer your question, even though I'm not sure you deserve any, the deprecated and non-deprecated methods have the same name, but the options are passed differently e.g.

```
dbConnection.Insert(entityToInsert, statement => statement.AttachToTransaction(dbTransaction));
```

The IDE will give you a hand in differentiating between the deprecated and non-deprecated form.

**Comment by fwd079** [comment]
Wow. The arrogance is strong with you mate. One should aspire instead of being touchy. 

But thank you nevertheless for providing an answer. IDE gave me a nice warning hence my question. I worked out proposed solution myself after downloading source and ended up creating few of my helpers. 

You however do deserve a thanks for prompt reply though. So, thank you for that. :)

Cheers.

**Comment by MoonStorm** [comment]
I'm touchy whenever I see comments like yours when it comes to a piece of free code released into the wild by one guy and having the nerve of comparing it with a behemoth like Microsoft. Is that ok with you? 

And what exactly am I supposed to aspire to exactly? Is there anything I'm gaining out of this? Fame? Fortune? Do you even see my real name anywhere?

**Comment by fwd079** [comment]
Geez. :D
Your real name is your progrative to hide what do you want me to say? I'm not sure  this should be such a big matter to be touchy about,  mate. 
Tell you what? I'll  post  you the xml comment if you want? 
As told I had already found solution but you were bit quick to respond here. Otherwise you'd have seen a thank you note and issue closed. :)

Cheers.
