### ISSUE TITLE
More of a question, but OrmConfiguration is static, so this means you can't have more than one database being used at one time?

### ISSUE THREAD

**Issue by xcalibre0** [MoonStorm/Dapper.FastCRUD#29]
My needs (which does not seem uncommon) require me to talk to different databases, identical in schema, but having different schema names.  This is a web service so could be many different threaded users.  OrmConfiguration is static, and its the only way I know of to change the schema used on queries.  

It seems like a common trend for these microOrms to use static facilities in such a way that makes them useless in non-trivial multi-tenant environments.  I'm hoping this is not the case, I like your project.

**Comment by MoonStorm** [comment]
``OrmConfiguration`` deals with overall settings and default conventions. Have a look at [Multiple mappings](https://github.com/MoonStorm/Dapper.FastCRUD/wiki/Multiple-mappings) which can be used for tweaking the mappings for the same db entities used in different circumstances.
