### ISSUE TITLE
Selecting certain columns

### ISSUE THREAD

**Issue by moxplod** [MoonStorm/Dapper.FastCRUD#30]
Have you thought about selecting certain columns only in select / get queries?

I was thinking of having an attribute which eliminates certain columns from a get query. The use case i am trying to solve is to eliminate large fields which will slow down select queries. So the query is 10x faster if the big ntext of nvarchar(max) field can be ignored. 

But when you are getting a single object you can include that field as part of the get.

What would you recommend be the best way to accomplish that?

**Comment by MoonStorm** [comment]
https://github.com/MoonStorm/Dapper.FastCRUD/wiki/Multiple-mappings ?

**Comment by moxplod** [comment]
Thanks for the pointer - will look into this.
