### ISSUE TITLE
Should Find return null or empty IEnumerable on no result.

### ISSUE THREAD

**Issue by moxplod** [MoonStorm/Dapper.FastCRUD#31]
The Find method is similar to EF Where method. Which always returns an empty IEnumerable (not nulll) when there are no results that match that query.

But here in FastCrud null is returned which means on every Find we have to do a null check. Should we be returning IEnumerable with no elements instead?

**Comment by MoonStorm** [comment]
Yes I was the impression that was the case. I'll take a look.

**Comment by moxplod** [comment]
Nvm - that is correct - for some reason one of my wrappers was returning null and i thought it was fastcrud.
