### ISSUE TITLE
Docs - Home - reformatting

### ISSUE THREAD

**Issue by jafin** [MoonStorm/Dapper.FastCRUD#33]
wrapped the home examples in code blocks as the angle brackets weren't visible (ie dbConnection.BulkDelete<Entity>();)

Added headings. 

I couldn't figure out how to submit wiki updates as a patch, sorry.

[Home.md.txt](https://github.com/MoonStorm/Dapper.FastCRUD/files/237921/Home.md.txt)

**Comment by MoonStorm** [comment]
I believe anyone with a github account can edit the wiki.

**Comment by jafin** [comment]
Ok see it now, thanks
