### ISSUE TITLE
Mysql: Entity __ has database generated fields that don't contain a primary key.

### ISSUE THREAD

**Issue by CameronFiederer** [MoonStorm/Dapper.FastCRUD#34]
Hello, I was attempting to use your repository with a Mysql database. I have an entity which has a composite primary key of which none of the keys are database generated. There is however a ModifiedTimestamp, which is calculated on insert and update. Sample Here:

```
    public class AggregatedRow
    {
        [Key]
        public int Id1{ get; set; }
        [Key]
        public string Id2{ get; set; }
        [Key]
        public string Id3 { get; set; }
        public int AggregateValue { get; set; }
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public System.DateTime ModifiedTimestamp { get; set; }
    }
```
Which is intended to correlate to the following table:

```
CREATE TABLE `AggregatedRow` (
  `Id1` int(11) NOT NULL,
  `Id2` varchar(255) NOT NULL,
  `Id3` varchar(55) NOT NULL,
  `AggregateValue` int(11) NOT NULL,
  `ModifiedTimestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`FileCollectionCycleId`,`StatusName`,`EventTimestamp`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```
When I attempt to insert into this table with FastCRUD, I get: 
```
Entity 'AggregatedRow' has database generated fields that don't contain a primary key.
```
Which looks like it is getting thrown from MySqlBuilder.ConstructFullInsertStatementInternal. It looks like my entity has a value of 0 for: InsertKeyDatabaseGeneratedProperties. Looking at the following code, it looks like those checks could be against KeyProperties == 0 instead. I'd make the pull request myself, but I'm not entirely sure if there's something I am missing.

If there's anything I can do to help, please let me know.

Also, thanks for the great work on this repo!

**Comment by MoonStorm** [comment]
Interesting. Can you check if it works without the ``DatabaseGenerated`` property?

**Comment by CameronFiederer** [comment]
Given the right conditional statement, could something like this work to construct the select statement?

`sql += $"SELECT {databaseGeneratedColumnSelection} FROM {this.GetTableName()} WHERE" + this.ConstructKeysWhereClause(this.GetTableName())`

**Comment by MoonStorm** [comment]
I don't think ``ConstructKeysWhereClause`` requires an alias but other than that it looks good. Could you create a PR? We're in the middle of the beta for 2.4.0 so this one couldn't have come at a better time.

**Comment by CameronFiederer** [comment]
Probably should have mentioned that I already started on it tonight: https://github.com/MoonStorm/Dapper.FastCRUD/pull/35.

**Comment by MoonStorm** [comment]
Thanks for providing a fix.  The existing tests all passed and a preview package is available on nuget.
