### ISSUE TITLE
How to Get Data From multiple tables using join conditions

### ISSUE THREAD

**Issue by k07** [MoonStorm/Dapper.FastCRUD#37]

**Comment by MoonStorm** [comment]
It's in the wiki

**Comment by k07** [comment]
"statement.**Include**<TableName>(join => join.InnerJoin()));"  
'Include' Is Not Supported in latest Stable Version(2.3.2),

**Comment by MoonStorm** [comment]
That's correct. It's part of the BETA for the time being. We just need more tests in that area before we can proceed with releasing a stable version.

**Comment by k07** [comment]
Ok Thanks...then how to join 2 more  tables using Stable version.?

**Comment by MoonStorm** [comment]
You can't. You're gonna have to use Dapper directly to achieve that.

**Comment by k07** [comment]
ok thank a lot.
