### ISSUE TITLE
Paging and Update

### ISSUE THREAD

**Issue by ehsaanwelcome** [MoonStorm/Dapper.FastCRUD#38]
Hi,
i really liked this library on top of dapper among other options.
I have seen mapping instruction which allows to update specific properties. is it possible to update properties from anonymous object or provide a list of properties at runtime?
.Update<User>({Id= 1, Name= "ABC"});
.Update<User>(user, statement => statement.onlyfields(u => u.Name));

this approach will be simple as OrmLite approach but that library is no more free to use.

For Paging, i have not seen any helper  .Paging(1, 10, sql)

I have a plan to use this library but my project update same entity in different ways and having custom mappings for every case is not a case so is it possible to add this as feature in future if it makes sense?

**Comment by MoonStorm** [comment]
I don't think you'll be seeing partial updates directly in the ``Update`` method. The idea behind default and custom entity mappings is that the SQL can be created once and reused in subsequent operations, reason why the overhead introduced by this library versus Dapper is minimal. 

For paging, you've got ``Top`` and ``Skip``. See [the wiki](https://github.com/MoonStorm/Dapper.FastCRUD/wiki) for some examples.

**Comment by ehsaanwelcome** [comment]
dbConnection.Find<Person>(statement => statement  
  .Where($"{nameof(Person.FirstName):C}=@FirstNameParam")  
  .OrderBy($"{nameof(Person.LastName):C} DESC")  
  .WithParameters(new {FirstNameParam: "John"}));

there is no .Select method to select particular columns?

**Comment by MoonStorm** [comment]
``WithEntityMappingOverride`` is what you're looking for. See [this topic in the wiki](https://github.com/MoonStorm/Dapper.FastCRUD/wiki/Multiple-mappings).
