### ISSUE TITLE
StrongName

### ISSUE THREAD

**Issue by Tolitech** [MoonStorm/Dapper.FastCRUD#40]
Hello, how are you?
First congratulations on the excellent work.

You can add the library one strongname?
How do I sign my library, I can not use his because it is not signed and is thus triggered an exception.

Thank you.

**Comment by MoonStorm** [comment]
We'll have a look, but I'm afraid one dependency used by this library doesn't have a strong name. Maybe this question on SO might be useful?
http://stackoverflow.com/questions/1379954/how-i-do-a-sign-an-assembly-that-has-already-been-built-into-a-dll-specifically

**Comment by Tolitech** [comment]
In my opinion, all Nuget library should be signed with strong name.
You can see that all projects signed exactly for this purpose. In addition to ensuring their release, who already subscribe to your own library can only use third-party libraries that are signed.

I think your project is very good and should be signed yes.
But larger projects may not use it.

Which library you use that is not signed?
StringInterpolationBridge?

You want me to try to contact the owner and ask him to sign the library?

If you want to understand a little about my project, I will post a video url here.
In case only the subtitle is in English.
https://www.youtube.com/watch?v=PzGSslwyTxg

I believe my libraries also have great access and therefore must be signed too.

Unfortunately if any is not signed, I will have to look for other libraries instead.

Anyway, I thank you in advance for your attention.

**Comment by MoonStorm** [comment]
That's a nice project you're working on. And believe me, I know where you're coming from. In a perfect world yes, we'd all be working with signed assemblies.

Speaking about our dependencies, ``StringInterpolationBridge`` is unsigned. But amazingly ``Dapper`` is another one! Most people use [this package on NuGet](https://www.nuget.org/packages/Dapper/), with more than 1.6 million total downloads. For some unknown reason they've decided to create a [separate package on NuGet](https://www.nuget.org/packages/Dapper.StrongName/), which is indeed signed, but having only 22,000 total downloads. 

Very few people care. Another reason could be that  nowadays we're dealing with so many 3rd party open-source projects that are being hosted in free repositories and built with free automated build services. And few are willing to invest time and even money to hide the keys in separate private repos.  So whoever goes the extra mile and decides to have their assemblies signed would most likely store the keys in plain sight, which defeats the purpose of signing the assemblies in the first place.

In any case, if you really wish to turn this into a personal crusade, I'd say that the ``StringInterpolationBridge`` is the showstopper here. I also don't understand why ``Dapper`` is using a separate package for its signed assemblies. That's just causing more problems.

**Comment by Tolitech** [comment]
Amazing.
I could have sworn that the Dapper was signed.
If I had bet, I lose the bet.
Really, I have no what to say.

I apologize that I have troubled you, for I have done wasting your time with it.
