### ISSUE TITLE
SQLite composite key not working 

### ISSUE THREAD

**Issue by hamish-tushar** [MoonStorm/Dapper.FastCRUD#41]
I see that entity having composite key for a SQLite database does not work. 
There is a exception throw in the code. 
Can you let me know how can I test my code with the SQLite and if there is a better alternative to do this

https://github.com/MoonStorm/Dapper.FastCRUD/blob/fb37c4a4796bc4482661b7feb9dd5802c955af79/Dapper.FastCrud/SqlBuilders/SqLiteBuilder.cs#L16

**Comment by MoonStorm** [comment]
At a first glance, that restriction shouldn't exist. Thanks for bringing this issue to our attention.
