### ISSUE TITLE
Having problem when querying / inserting using MariaDB.

### ISSUE THREAD

**Issue by dsoronda** [MoonStorm/Dapper.FastCRUD#44]
I got this exception:

`You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '[ID],[CompanyID],[FirstName],[LastName] FROM [Persons] WHERE [ID]=4' at line 1`

I tried latest nuget package MySql.ConnectorNET.Data by Oracle (v. 6.8.3.2) and latest [6.9.9](http://dev.mysql.com/downloads/connector/net/).

Any suggestions ?

**Comment by MoonStorm** [comment]
Do you have the following line in your app startup?
``OrmConfiguration.DefaultDialect = SqlDialect.MySql``

**Comment by dsoronda** [comment]
Wow, sorry my bad.
I was too eager to try it that I didn't take a look at Wiki pages.

Will close this issue.
