### ISSUE TITLE
DOTNET Core support

### ISSUE THREAD

**Issue by dsoronda** [MoonStorm/Dapper.FastCRUD#45]
Is there any support for .NET Core ?

**Comment by MoonStorm** [comment]
Yes, version 2.4.0 supports .NET Standard 1.6 aka .NET Core 1.0

**Comment by dsoronda** [comment]
So, can you put that kind of information on main page?
I think it it valuable information for users.

Thanks

**Comment by MoonStorm** [comment]
Sure. I've updated the [wiki](https://github.com/MoonStorm/Dapper.FastCRUD/wiki/Installation). This information is also available on the NuGet site and also in the NuGet package manager.
