### ISSUE TITLE
Get with Include fails with multiple related entities

### ISSUE THREAD

**Issue by Jbond312** [MoonStorm/Dapper.FastCRUD#46]
I'm having trouble getting your example code to work from the wiki under the 'Joins' section. I've created the relevant database objects, etc. I have a single workstation that has multiple employee's. However, when executing the following code:

```
con.Get(new Workstation {WorkstationId = workStationId },
                    statement => statement.Include<Employee>()));
```

An exception is thrown:

`Sequence contains more than one element`

Stack trace if useful:

```
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Dapper.FastCrud.SqlStatements.RelationshipSqlStatements`1.SelectById(IDbConnection connection, TEntity keyEntity, AggregatedSqlStatementOptions`1 statementOptions)
   at DapperCore.Repository.Repository.GetWorkstation(Int32 workStationId) in C:\W\DapperCore\DapperCore\src\DapperCore\Repository\Repository.cs:line 28
   at DapperConsole.Program.Main(String[] args) in C:\W\DapperCore\DapperCore\src\DapperConsole\Program.cs:line 23
```

It doesn't seem to be able to handle the fact that the `Workstation` has many `Employee` objects associated with it.

If I remove the Employee's from the database so that there is only a one-to-one relationship between the two. The code above works fine and I get only a single `Employee `object in the collection.

**Comment by VictorTomaili** [comment]
try yo use reverted query like `con.List<Employee>(statement => statement.Include<Workstation>().Where(Workstation.Fields.WorkstationId = workstationId));`

**Comment by Jbond312** [comment]
Maybe I'm missing something. FastCrud doesn't appear to expose a `List` method. Did you mean `Find`? 

The `Find` method doesn't appear to give me the output I'd expect (which may just be my understanding). If I had 3 Workstations, each with 2 Employee's. I'd expect to receive 3 workstation objects, with the 2 Employee objects. However, I actually end up with 6 Workstation objects with 2 Employee's, which is the output you'd expect to see if you ran the SQL query itself. However, is any aggregation supposed to occur on the objects that get created to prevent this "duplication"?

Is the 'Get'  method ever intended to be able to handle my initial scenario?

I understand that this is still in Beta but just want to understand how this should work.

**Comment by MoonStorm** [comment]
It seems as if the parent entities fail to be aggregated. Are they properly set (i.e. does FastCrud know about their primary keys)? And if they do, what type is that key? Could you check if indeed 3 of those 6 parent entities have identical keys?

**Comment by Jbond312** [comment]
I believe so. The classes I'm using are as per the Wiki:

```
    public class Employee
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int EmployeeId { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public DateTime BirthDate { get; set; }
        // marks a foreign key and also points to the property holding the related entity
        [ForeignKey("Workstation")]
        public int? WorkstationId { get; set; }
        public Workstation Workstation { get; set; }
    }

    public class Workstation
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int WorkstationId { get; set; }
        public string Name { get; set; }
        public int AccessLevel { get; set; }
        public int InventoryIndex { get; set; }
        public IEnumerable<Employee> Employees { get; set; }
    }
```
The only difference being that I'm using integers as the keys instead of a guid/long.

I've manually debugged this now (the 'Get' method) and can see where the problem is occurring. For example, in the `TwoEntitiesRelationshipSqlStatement `class. It has a `Query` method that calls Dappers own `Query` method which can take a func (which is used to map objects manually). The func will fire for each row returned from the Db and return an instance of TMainEntity. Behind the scenes we are building (`RelationshipEntityInstanceBuilder`) up the same instance of this TMainEntity object with all of it's related entities, adding a new child entity for each row:

```
                (mainEntity, joinedEntity) =>
                {
                    relationshipInstanceBuilder.RegisterResultSetRowInstance(ref mainEntity);
                    relationshipInstanceBuilder.RegisterResultSetRowInstance(ref joinedEntity);
                    relationshipInstanceBuilder.EndResultSetRow();

                    return mainEntity;
                },
```

Ending up with an IEnumerable<TMainEntity> being returned from the method. So in my example for `Get`. If I had a Workstation with 3 employee's. I'd get back 3 Workstations (that point to the same object in memory). The problem occurs when `.SingleOrDefault()` is then used on the return value of the method within the `RelationshipSqlStatements` class on the `SelectById` method as there will always be more than one object returned if multiple child entities are associated with it. Causing the exception to be thrown.

We somehow need to perform a `Distinct` on the objects being returned as we know they are the same object instances. The other option is that there could be a better way to achieve this mapping outside of the use of the Func<>. This issue will be the same type of duplication I'm seeing when calling 'Find` as well.

**Comment by MoonStorm** [comment]
I believe I found the problem. The algorithm is creating unique entities but isn't using that information later on. The fix should be trivial.

**Comment by MoonStorm** [comment]
Fixed and released. Give it a shot but be aware that Dapper is suffering from a [bug](https://github.com/StackExchange/dapper-dot-net/issues/596) that cause the async methods to fail.
