### ISSUE TITLE
MySql: Building queries using limit clause

### ISSUE THREAD

**Issue by deluvas** [MoonStorm/Dapper.FastCRUD#48]
Hi,

How can I construct my queries with the statement builder to use the `LIMIT` clause?
E.g.

```
connection.Find<Entity>( st => st.Limit( 100 ) ); // select * from entity limit 100
```

I've been through the code and wiki, but I can't find a solution. What am I missing here?
Thanks.

**Comment by MoonStorm** [comment]
Isn't there a ``Top`` method on the statement?

**Comment by deluvas** [comment]
There is, but it cannot be used without OrderBy, which is not the case in MySql.

**Comment by MoonStorm** [comment]
It is the case with any SQL engine out there, including MySql, even if it doesn't blow up on execution. The order of the queried records is undefined without an ORDER BY. You MUST order by something.

**Comment by deluvas** [comment]
I'm indifferent about the order of the returned records in this case. 

Using just the LIMIT clause is syntactically correct as far as the manual goes and IMO a query builder should follow that.

**Comment by MoonStorm** [comment]
That's a fair point. I'll look into turning the validation off.
