### ISSUE TITLE
Insert should really return an id.

### ISSUE THREAD

**Issue by generik0** [MoonStorm/Dapper.FastCRUD#53]
Hi

Very nice package. Great work! One issue.  Insert should return an id. Pref a generic if possible.
Check: Dapper.Contrib Dapper.SimpleCRUD.

Seams to be a common requirement.

Great work.

**Comment by MoonStorm** [comment]
It does. Check your entity on return.

**Comment by generik0** [comment]
OK. So you update the entity.. Great mate!

**Comment by MoonStorm** [comment]
Yep. Primary keys, even composite ones, DB generated values in general, are all set up on the entity.
