### ISSUE TITLE
Async methods?

### ISSUE THREAD

**Issue by moxplod** [MoonStorm/Dapper.FastCRUD#6]
I did not see async methods in FastCRUD. Do you have those overloads? Any plans to add them?
Given that FastCRUD's focus is on speed. 
Providing async overloads would help achieve more efficient use of server resources.

**Comment by MoonStorm** [comment]
Agreed, will be included in a future release.

**Comment by MoonStorm** [comment]
Thanks for your work. Async methods are now part of 2.1.
