### ISSUE TITLE
BulkDelete where in ...

### ISSUE THREAD

**Issue by vitidev** [MoonStorm/Dapper.FastCRUD#60]
Is it possible to make such a?

    dbConnection.BulkDelete<Asset>(statement => statement  
      .Where($"{nameof(Asset.Id) IN ...")
      .WithParameters(new { ... = assets});

**Comment by generik0** [comment]
I think you are missing a bracket..

What is the raw sql query you are trying to use, in full?

**Comment by vitidev** [comment]
Raw dapper equivalent. Only example. Full case I have described [here](https://github.com/MoonStorm/Dapper.FastCRUD/issues/58)

    interface IEntity{
         long Id {get;set;}
    }

    public void EntityBulkDelete(IEnumerable<IEntity> entities){
          db.Execute($"DELETE FROM assets WHERE Id IN @Ids",
                    new {Ids = entities.Select(e => e.Id).ToArray()});
    }

but we need to know tablename for raw sql.
`EntityBulkDelete<T>` is impossible in my case, so I can not use `OrmConfiguration.GetDefaultEntityMapping<T>()`

**Comment by generik0** [comment]
Hmm, so we are back a little to the previous issue, that your IoC is not injecting with Generics.
have you tried the syntax's on the wiki: https://github.com/MoonStorm/Dapper.FastCRUD/wiki/SQL-statements-and-clauses. 

i.e. {nameof(Asset.Id):C}

You can probably do some tests with the sqlbuilder to get it right. After all FastCRUD is just creating queries for you...

**Comment by vitidev** [comment]
Let's forget about the IoC and generics problem in **this** issue. 

If we can 

    db.BulkDelete<Asset>(
                    stmt =>
                        stmt.Where($"{nameof(Asset.Id)} IN @Ids")
                            .WithParameters(new { Ids = idList }));

why not add a useful feature?

    db.BulkDelete<Asset>(assets);

which delete records by primary key. 

FastCrud **is micro-orm** and we have `db.Insert(entity)` and `db.Delete(entity)` and even `db.Delete(entity)`, but why we have no method `db.BulkDelete(entities)`?

**Comment by generik0** [comment]
Your right :-)
You can add it yourself to the project and do a pull request? Otherwise we will have to wait til MoonStorm is back...
Sorry I could not help more...

**Comment by ducman** [comment]
If I understand correctly, you want FastCrud to support bulk delete by primary key?

I don't think this is necessary in this library. The bulk delete method already expose the where clause/parameters for you to wrap it to create any other methods you need. 

Besides, FastCrud support composite primary key, how would you go able supporting bulk delete with composite primary key? I'm sure it can be done, but I bet it's going to be complex/messy.

In the end, I think it's up to you to write custom wrapper (extension) methods to help do what you need in your application.

**Comment by vitidev** [comment]
@ducman

>you want FastCrud to support bulk delete by primary key?

Yes, and why not? We can do all things through raw dapper. FastCRUD extends Dapper for more comfortable work with "entities".  Is the mass deletion of entities by primary key is a rare operation? I do not think so.

>delete with composite primary key

Nothing. I just will not call BulkDelete in this case. And I would not be surprised if I get an exception "Composite keys is not supported". 

>I think it's up to you to write custom wrapper (extension) methods to help do what you need in your application.

You are right. But I think the mass deletion of entities is enough common operation to be in FastCRUD and not be an extension, which is copied to every project.

**Comment by ducman** [comment]
I agree with you but if the author decides to do it, he/she has to write it to support composite primary keys since the library support it.

**Comment by MoonStorm** [comment]
We have reviewed all the existing CRUD methods for 3.0 and made several critical improvements. Please check the list of changes [here](https://github.com/MoonStorm/Dapper.FastCRUD). We'll update the wiki shortly.
