### ISSUE TITLE
Default Tablename convension

### ISSUE THREAD

**Issue by generik0** [MoonStorm/Dapper.FastCRUD#62]
Hi

Thanks for a great package. Is there anyway to overide the default convension for table names.
So it does not use the plural.

It Class "Foo" has table name "Foo" not Foos".
I know i can add the Table["Foo"] attribute to the class, but is it really needed?

Thanks, BR Rik

**Comment by MoonStorm** [comment]
[The wiki](https://github.com/MoonStorm/Dapper.FastCRUD/wiki/Default-library-conventions) might give you some pointers.

**Comment by generik0** [comment]
Sorry mate. I have read the wiki up and Down everywhere Else. But I missed this..

Thanks again...

**Comment by JeancarloFontalvo** [comment]
Hi, first of all, thanks for this wonderful tool <3. I have this problem with a simple Query with `Find` method,  I've tried many ways but cannot get it to work. 

This is my code, in my Software Repository: 
``` csharp
    override public IEnumerable<Software> FindAll()
    {
        IEnumerable<Software> softwares = new List<Software>();

        using (IDbConnection dbConnection = connection)
        {
            dbConnection.Open();
            softwares = dbConnection.Find<Software>();
         }
         return softwares;
     }
```
Pretty simple, right? A simple Query to test the Library 😄. And this is my Entity:

```csharp
     public class Software : OrmConventions
     {
        [Key]
        [ColumnAttribute("Id_Software")]
        public int id { get; set; }

        [ColumnAttribute("Descripcion_Software")]
        public string descripcion { get; set; }

        [ColumnAttribute("Version")]
        public string version { get; set; }

        [ColumnAttribute("Activo")]
        public bool activo { get; set; }

        override public string ToString() 
        {
            return JsonConvert.SerializeObject( this, Formatting.Indented );
        }

        override public string GetTableName(Type entityType) {
            return "SOFTWARE";
        }

        override public string GetSchemaName(Type entityType) {
            return "MAESTRAS";
        }
        
    }
```

I tried to execute, this many times, (chaning the methods, or using the Table Attribute, but does not work 😢. This is what I got: 

`Unhandled Exception: System.Data.SqlClient.SqlException: Invalid object name 'Softwares'.`

**Comment by generik0** [comment]
I think you need a Table attribute with your table name: software. It is defaulting to Softwares

**Comment by JeancarloFontalvo** [comment]
Hi Mister @generik0, thanks for reply.

I've already tried with the `Table("SOFTWARE")` attribute, but I got the same error.

I'm using it with .NetCore

**Comment by generik0** [comment]
Interesting.

- Why did you inherit the ormconvensions?
- What dB are you using ? 
- Did you set the dialog?

**Comment by JeancarloFontalvo** [comment]
Hi, thanks for keep replying. 

- **Why did you inherit the ormconvensions?**
Ok I was reading the wiki, and It says that you can derive your POCOs from this Class to override some methods
- **What dB are you using ?**
 **SQL Server**, the table name is `MAESTRAS.SOFTWARE`
- **Did you set the dialog?**
Ok I don't get this one • - • 😮

**Comment by generik0** [comment]
Hi
Just to be sure. Set the dialog (from wiki);

OrmConfiguration.DefaultDialect = SqlDialect.MsSql|MySql|SqLite|

Try without the inheritence, But you at correct, it should inherit fine.
But lets Keep it simple to start with and just ise the attributes...

**Comment by JeancarloFontalvo** [comment]
@generik0  Well, Mister... the problem was happening because the micro-ORM was looking for the name "Software" without the schema name, so I ended up with this:

`[Table("SOFTWARE", Schema = "MAESTRAS" )]`

And it worked 😄 ! Thanks for your help.

PD: I read this [tutorial](http://www.entityframeworktutorial.net/code-first/table-dataannotations-attribute-in-code-first.aspx), so I learnt the `Schema` property from the `Table `Attribute 😮
