### ISSUE TITLE
statementOptions iteration

### ISSUE THREAD

**Issue by generik0** [MoonStorm/Dapper.FastCRUD#63]
Hi

I know this might sound a little werid. You will just have to trust me that it actually makes sence.

Is there any way i can invoke (or whatever) the statementOptions and iterate over the Include generics / types?

Best Regards

**Comment by MoonStorm** [comment]
No. The statement options are always exposed as interfaces with internal implementations. You're gonna have to find another way.

**Comment by generik0** [comment]
OK. Thanks.
