### ISSUE TITLE
NotMapped attribute

### ISSUE THREAD

**Issue by jafin** [MoonStorm/Dapper.FastCRUD#64]
This wiki page has an example with [NotMapped]  is that just a doco bug or should it allow a property to not be used in a Query? https://github.com/MoonStorm/Dapper.FastCRUD/wiki/Entity-registration

**Comment by generik0** [comment]
I have used [NotMappedAttribute] to stop the query mapping a property.
Its not a bug or anything. It works!

**Comment by jafin** [comment]
@generik0 Ok thanks, I've obviously done something wrong then, I'll try and isolate a test case.

**Comment by jafin** [comment]
Found _my_ issue.  Was using Dapper.NotMapped from Dapper.SimpleCRUD  not  System.ComponentModel.DataAnnotations.Schema.NotMapped
