### ISSUE TITLE
Multiple joins to same table

### ISSUE THREAD

**Issue by draunkin** [MoonStorm/Dapper.FastCRUD#65]
I was wondering how it is possible to 'alias' table names when doing multiple joins, using different foreign keys and different mapped properties to the same table.  

Note: I've had to create different concrete types of the Contact table to avoid a different error in the join.

My basic entity structure looks like

```
[Table("ParentTable")]
public class DbParentTable
{
    [Key]
    public int ParentTableId { get; set; }

    [ForeignKey("InterestingContact")]
    public int? InterestingContactId { get; set; }
    public DbInterestingContact InterestingContact { get; set; }

    [ForeignKey("AnotherInterestingContact")]
    public int? AnotherInterestingContactId { get; set; }
    public DbAnotherInterestingContact AnotherInterestingContact { get; set; }
}

[Table("Contact")]
public class DbContact
{
    [Key]
    public int ContactId { get; set; }
    public string ContactReference { get; set; }
}

public class DbInterestingContact : DbContact { }

public class DbAnotherInterestingContact : DbContact { }

```

Then when I query using the following approach, It produces sql where the selects and the joins are all done with the same table name (Contact). Which is why I would like to alias them.

```
dbCon.Get(new DbParentTable() {ParentTableId = id},
              x => x.Include<DbInterestingContact>(i => i.InnerJoin())
                    .Include<DbAnotherInterestingContact>(i => i.LeftOuterJoin()));
```

I've noticed you have the option to use a table alias in the SqlBuilder. However we do not desire to use the builder directly as it seems like a step in the wrong direction when the internal builder is 99.9% there for us.
Do you have any option to alias using attributes or the fluent orm configuration?

Thanks

**Comment by justshrey** [comment]
@draunkin 
At the moment, the work-around we have is to just mark the relevant properties as NotMapped .
in the example above , we mark both the DbContact as NotMapped, and the the joins  work without any errors. 


@MoonStorm Hi, I am quite interested to build this up as an enhancement. 

This kind of relationship is quite common and might be useful to add to the core library . I guess we could use  Foreign Key attribute value as an alias for the specific table? am guessing I should start here 

https://github.com/MoonStorm/Dapper.FastCRUD/blob/master/Dapper.FastCrud/Configuration/OrmConventions.cs#L214 

and see where it leads?



I also have an updated version of the  GenericModelGenerator.tt which has two additional options 

1.  Ability to specify an additional options parameter which could control the generation of ForeignKeys relationships. For instance , setting an option as given below , would generate two keys  instead of one as in the current scenario



```C#
ForeignKeyNameList = new Dictionary<string,KeyNames>(){
				{ "FK_DBParents_InterestingContact", new KeyNames() {Name="FK_DBParents_InterestingContact",OuterKeyName="InterestingContact",InnerKeyName="InterestingParentTables"}},
				{ "FK_DBParents_AnotherInterestingContact", new KeyNames() {Name="FK_EntityRelationships_SecondaryEntity",OuterKeyName="AnotherInterestingContact",InnerKeyName="AnotherInterestingParentTables"}}
}

```
would generate

```C#
[Table("ParentTable")]
public partial class DbParentTable
{
    [Key]
    public virtual int ParentTableId { get; set; }

    //ForeignKey Name: FK_DBParents_InterestingContact
    [ForeignKey("InterestingContact")]
    public virtual int? InterestingContactId { get; set; }
    public virtual DbContact InterestingContact { get; set; }

    //ForeignKey Name: FK_DBParents_AnotherInterestingContact
    [ForeignKey("AnotherInterestingContact")]
    public virtual  int? AnotherInterestingContactId { get; set; }
    public virtual DbContact  AnotherInterestingContact { get; set; }
}

[Table("Contact")]
public class DbContact
{
    [Key]
    public int ContactId { get; set; }
    public string ContactReference { get; set; }
  
    // ForeignKey (InnerKey): FK_DBParents_InterestingContact
    public virtual IEnumerable<DbParentTable> InterestingParentTables{ get; set; }

    // ForeignKey (InnerKey): FK_DBParents_AnotherInterestingContact
    public virtual IEnumerable<DbParentTable> AnotherInterestingParentTables{ get; set; }
}

```

2. Ability to generate classes in separate files instead of a single file.  ( Taken from the standard EF generator )

3. Ability to derive from a Base class

I was thinking of adding these once we have proper multiple mapping other wise as its stands Joins don't work with the structure as above. 

Your thoughts?

**Comment by MoonStorm** [comment]
The point of using the attributes from the data model annotation namespace was that they keep following their documented usage in MSDN.

I discovered that, for this kind of scenarios, EF uses an [InverseProperty](https://msdn.microsoft.com/en-us/data/jj591583?f=255&MSPPError=-2147217396#Relationships). I'm curious whether that attribute is available in the same namespace as all the other ones.

**Comment by justshrey** [comment]
Good point!... Makes total sense! I think implementing the InverseProperty  would be a great idea. 
 
Its in the same namespace as the ForeignKey attribute.  

`System.ComponentModel.DataAnnotations.Schema.InversePropertyAttribute`

**Comment by draunkin** [comment]
Be great to see it implemented, thanks justshrey for taking up the request

**Comment by CharlesSchneider** [comment]
I'm running in the same problem. It will be fixed? I tried some of your examples, but none of them worked for me.

**Comment by PlasticLizard** [comment]
I'm in the same boat - tried everything I can think of with no love - I use this pattern quite frequently though in my modeling, so if there is any example of how it could work, even if kludgy, would be great to see.

**Comment by justshrey** [comment]
Yes, it will be . Been a bit too caught up on the work front so haven't been able to finish testing and push it in. Should have some time next week so  will see if i can finish this.

In the meanwhile,  what exactly is the issue you are facing? . At the moment, the NotMapped attribute workaround works without an issue and you will be able to work with the select statements. 

Currently, I fill these mapped fields manually at the repository stage.

**Comment by PlasticLizard** [comment]
I am getting a duplicate name SQL error, no matter where I put the NotMapped attribute - any chance you could post a brief example of that attribute in the right place if you happen to have a chance? My use case is exactly as the example above, but I tried Not Mapped everywhere I could think of and it didn't seem to change the error.

**Comment by justshrey** [comment]
It may not be your code per say.

Are you using the latest code from Github? I think it has the fix in the recent commits to master branch which hasn't been formally released yet. 

You need to put the notmapped attribute on the object references. In the example above it would be at 
```C#
[Table("Contact")]
public class DbContact
{
    [Key]
    public int ContactId { get; set; }
    public string ContactReference { get; set; }
  
    // ForeignKey (InnerKey): FK_DBParents_InterestingContact
    [NotMapped]
    public virtual IEnumerable<DbParentTable> InterestingParentTables{ get; set; }

    // ForeignKey (InnerKey): FK_DBParents_AnotherInterestingContact
    [NotMapped]
    public virtual IEnumerable<DbParentTable> AnotherInterestingParentTables{ get; set; }
}

**Comment by MoonStorm** [comment]
This scenario is now supported. I just added some tests with multiple JOINs pointing back to the same entity and they are passing. The whole relationship logic had to be redone for 3.0.  We'll update the wiki soon.
