### ISSUE TITLE
How to configure many to many relationshops

### ISSUE THREAD

**Issue by svdhorst** [MoonStorm/Dapper.FastCRUD#69]
I have User instances and UserRole instances. There is a many to many relationship between these two classes. My sql schema contains a User Table, a UserRole table and a UserUserRole table. The primary key of all tables is set to Id (int). UserUserRole holds a foreign key to User as well as to UserRole.

Now when I perform a join, fastcrud actually joins the User on Userrole and it does not take the UserUserRole in account.

User class:
  [Table("User")]
    public partial class User : BaseEntity
    {
    public int Id {get;set;}
        /// <summary>
        /// Gets or sets UserRole Mappings
        /// </summary>
        public IEnumerable<UserRole> UserRoles { get; set; }
    }

UserRole class
 [Table("UserRole")]
    public partial class UserRole : BaseEntity
    {
    public int Id {get;set;}

        /// <summary>
        /// Gets or sets User Mappings
        /// </summary>
        public IEnumerable<User> Users { get; set; }
    }

entity is of class User with a valid Id

var ent = uow.Transaction.Connection.Get(entity, x=>x.Include<UserRole>(join => join.InnerJoin())
                                                                        .AttachToTransaction(uow.Transaction)
                                                                        .WithTimeout(TimeSpan.FromSeconds(10)));

This actually creates the following sql statement
SELECT [User].[Id],[UserRole].[Id] FROM [User] JOIN [UserRole] ON ([User].[Id]=[UserRole].[Id]) WHERE ([User].[Id]=@Id)

However this sql is a one to one relationship

What would be the propert pattern to implement a many to many relationship?

thx
Stefan

**Comment by MoonStorm** [comment]
You need the ``UserUserRole`` entity in there as well, properly defined and mapped. You then create a a three entity join in ``FastDapper``

**Comment by svdhorst** [comment]
Ok Got it. Pitty that it will consume one of the max seven join entities.

**Comment by generik0** [comment]
But it would do so with Dapper also ....
