### ISSUE TITLE
How to setup a gen-spec mechanism

### ISSUE THREAD

**Issue by svdhorst** [MoonStorm/Dapper.FastCRUD#72]
I currently have the following base class

```
[Table("LedgerAccount")]
public partial class LedgerAccount: BaseEntity
 {
        [Key()]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [MaxLength(7)]
        public string AccountCode { get; set; }
}
```

Next I define a subclass of LedgerAccount, being Creditor:
```
[Table("Creditor")]
public partial class Creditor : LedgerAccount
{
        /// <summary>
        /// Gets or sets the BankBICSWIFT
        /// </summary>
        [MaxLength(20)]
        public string BankBICSWIFT { get; set; }
}
```
(The Creditor and LedgerAccount tables share an identity column ID whereby LedgerAccount can create the identity and the Creditor table simply copies the id)

Now when I perform a Get<Creditor> the sql statement that is generated only reads data from the Creditor table. It then returns an error stating that AccountCode is an invalid columnname. The SQL statement does not contain a join with the LedgerAccount table. The sql is 

SELECT [BankBICSWIFT],[AccountCode], [Id] FROM [Creditor]
whereas I would expect
SELECT [BankBICSWIFT],[AccountCode], Creditor.[Id] FROM [Creditor] inner join [LedgerAccount] on Creditor.id = LedgeraccountIid

How can I instruct FastCrud to include the superclass table 'LedgerAccount'?

**Comment by MoonStorm** [comment]
Two classes in an inheritance pointing to different tables? You should think of the problem from a different angle. These two entities should be separate and linked together via [JOINs](https://github.com/MoonStorm/Dapper.FastCRUD/wiki/JOINs).

**Comment by svdhorst** [comment]
That is indeed how I ended up implementing it but thx for letting me know that we think alike.
