### ISSUE TITLE
Overriding the default _entityListType for associations

### ISSUE THREAD

**Issue by svdhorst** [MoonStorm/Dapper.FastCRUD#73]
When I look at class RelationshipEntityInstanceBuilder there is a variable with assignment

_entityListType = typeof(List<>)

I presume this _entityListType is used for associations.

I would like to register my own IList<> because that would allow an integrated CRUD mechanism to become a part of the list.

**Comment by MoonStorm** [comment]
I guess that type could come from the [library settings](https://github.com/MoonStorm/Dapper.FastCRUD/wiki/Default-library-conventions).

**Comment by svdhorst** [comment]
Yes indeed. For now I will run the List<T> result through my NopList<T>:IList to add the CRUD functionality but if we were to have the type setting in the future then that would improve speed.

**Comment by MoonStorm** [comment]
Added in 3.0.
