### ISSUE TITLE
MSSQL Offset & Fetch without orderby

### ISSUE THREAD

**Issue by VictorTomaili** [MoonStorm/Dapper.FastCRUD#8]
There is a issue. I must add order by for offset and fetch. 
![VSError](http://img.prntscr.com/img?url=http://i.imgur.com/2QT6sar.png)

![SqlError](http://img.prntscr.com/img?url=http://i.imgur.com/fcNnYym.png)

![SqlOrderby](http://img.prntscr.com/img?url=http://i.imgur.com/hAnOHTt.png)

[SqlBuilders/MsSqlBuilder.cs](https://github.com/MoonStorm/Dapper.FastCRUD/blob/1d713a2b95b5632aa4b88c2ffbf4aaa1d55e8404/Dapper.FastCRUD/SqlBuilders/MsSqlBuilder.cs) 
There is fix

```c#
    public override string ConstructFullBatchSelectStatement(
            FormattableString whereClause = null,
            FormattableString orderClause = $"1",
            int? skipRowsCount = null,
            int? limitRowsCount = null,
            object queryParameters = null)
```

**Comment by MoonStorm** [comment]
That is a very bad idea. [The database never guarantees to give you the records in a certain order, even when a clustered index is present](http://blogs.msdn.com/b/conor_cunningham_msft/archive/2008/08/27/no-seatbelt-expecting-order-without-order-by.aspx). You should always use an ORDER BY clause for returning a page of records or a number of top most records.

**Comment by VictorTomaili** [comment]
you are right, but also need something for possible mistakes. All programmers doesnt see this mistake. I'm also spend some minutes for this.

**Comment by MoonStorm** [comment]
True, the actual fix should be to add some validation on those parameters.
