### ISSUE TITLE
Request ability to dynamically "build up" the where clause

### ISSUE THREAD

**Issue by kgday** [MoonStorm/Dapper.FastCRUD#80]
Currently it is not possible to "build up" a where clause based on a number of conditions because you cannot append FormattableString's together.  Maybe could be done with a custom FormattableString type.  But I am not sure how that could be done to override the class that the FormattableStringFactory uses to create the string when using $

**Comment by kgday** [comment]
I think I have found a way to build up the where clause.

**Comment by fuzzzerd** [comment]
@kgday What did you end up doing? I think that'd be a great feature as it seems multiple calls to `.Where` simply override the previous ones.

**Comment by kgday** [comment]
@fuzzzerd I built it via the where string e.g.

```
FormattableString where = null;
if (something)
{
  if(where == null)
    where = $"";
  else
    where = $"{where} and";
  where =  $"{where} {nameof(Entity.FirstName):C}=@FirstNameParam}";
}
if(somethingElse)
{
  if(where == null)
    where = $"";
  else
    where = $"{where} and";
  where =  $"{where} {nameof(Entity.LastName):C}=@LastNameParam}";
}
dbConnection.Find<Entity>(statement => statement  
                .Where(where)
                .Orderby($"{nameof(Entity.PrimaryPhoneNo):C}")
                .WithParameters(new {FirstNameParam = "John", LastNameParam = "Smith"});
```

However in some cases, because of complex joins, and those joined entities being a part of the where clause, I had to use the sql builder classes and build up actual sql since it was not possible to do what I needed otherwise at present.

**Comment by fuzzzerd** [comment]
@kgday Thanks. That looks good.

**Comment by MoonStorm** [comment]
Open this issue again if you still need help.
