### ISSUE TITLE
Mismatch in the number of properties that are part of the relationship between 'PerformanceTest.Models.Apm' (0 properties) and 'PerformanceTest.Models.Bpm' (1 properties)

### ISSUE THREAD

**Issue by arvand** [MoonStorm/Dapper.FastCRUD#81]
I have two sample entities:

    [Dapper.Table("Apms")]
    public class Apm
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string Name { get; set; }
        public string BigText { get; set; }
        public DateTime? DateOfBirth { get; set; }
        public decimal Height { get; set; }
        public float Weight { get; set; }

        public IEnumerable<Bpm> Bpms { get; set; }
    }

    [Dapper.Table("Bpms")]
    public class Bpm
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string Name { get; set; }
        public string BigText { get; set; }
        public DateTime? DateOfBirth { get; set; }
        public decimal Height { get; set; }
        public float Weight { get; set; }
        [ForeignKey("Apm")]
        public int? ApmId { get; set; }
        public Apm Apm { get; set; }
    }

But when using the code below:

               var b = connection.Find<Apm>(statement => statement
                     .Include<Bpm>(join => join.LeftOuterJoin()))
                     .ToList();

I get the error:
Mismatch in the number of properties that are part of the relationship between 'PerformanceTest.Models.Apm' (0 properties) and 'PerformanceTest.Models.Bpm' (1 properties)

Can anyone help me to identify the problem?

**Comment by kipusoep** [comment]
Yeah same issue here...

**Comment by jose8789** [comment]
Did you solve the problem? I have the same issue here!

**Comment by Abbas-Hashemian** [comment]
Solution : I had a different situation, (2 properties) to (1 property) just make sure SetPrimary(false) for the ID column is set on that entity having 2 properties. We had a Guid as PK and an auto-incremental ID column too but I forgot to exclude ID from PKs. You may have a different situation but check your db table for PK cols and set the config accurately.
