### ISSUE TITLE
How to specify SqlDialect for a specific query?

### ISSUE THREAD

**Issue by VictorGavrish** [MoonStorm/Dapper.FastCRUD#82]
I know of only one way to specify the `SqlDialect` - to use `OrmConfiguration.DefaultDialect`. However, I need to use both MS SQL Server and PostgreSQL Server in the same application. Is there a way to do that?

**Comment by generik0** [comment]
Yes it is. you can setup for each entity.
Look at my helper package:
https://github.com/generik0/Smooth.IoC.Dapper.Repository.UnitOfWork

Find method SetDialogueIfNeeded

<code>
mapping = OrmConfiguration.GetDefaultEntityMapping<TEntity>(); //reload to be sure
                    if (mapping.IsFrozen || mapping.Dialect == sqlDialect) return;
                    mapping.SetDialect(sqlDialect);
<code/>

**Comment by MoonStorm** [comment]
Reopen this if you still need help.
