### ISSUE TITLE
Incorrect multiple JOIN

### ISSUE THREAD

**Issue by belpyro** [MoonStorm/Dapper.FastCRUD#86]
Hello!
I have three classes (Category is very simple class), that I configured run-time over OrmConfiguration:

Class A
{
  public int CategoryId {get;set;}

  public virtual Category MyCategory {get;set;}
}

Class B
{
  public int CategoryId {get;set;}

  public Category MyCategory {get;set;}

   public int ParentId {get;set;}

   public virtual A Parent {get;set;}
}

// test get (just for example)
```
var result = connection.Get<B>(new obj with Id, 
statement => statement.Include<A>().Include<Category>());
```

And I get incorrect Join Sql, like as: "LEFT OUTER JOIN [Category] ON ([B].[CategoryId]=[Category].[Id])([A].[CategoryId]=[Category].[Id]) "

What's wrong? Could you help me with resolving the issue?

**Comment by belpyro** [comment]
As I can see issue is in code:
```
this.FindRelationship(firstEntitySqlBuilder, secondEntitySqlBuilder, out firstEntityPropertyMappings, out secondEntityPropertyMappings, ref secondEntityFinalJoinType);

                        if (firstEntityPropertyMappings == null || secondEntityPropertyMappings == null)
                        {
```
we have not null firstEntityMapping and secondMapping twice and we run
`joinClauseBuilder.Append('(');` also twice.
I think we need to add possibility to set table alias and check that joinClauseBuilder not empty. IMHO.
I hope my things help you with issue resolving.

P.s. Library really cool but it's blocker for using in my project.

**Comment by MoonStorm** [comment]
The relationships have been completely reworked for 3.0 and support for aliases has been included.

**Comment by MoonStorm** [comment]
If you're still experiencing problems with the latest version, please reopen this issue.
