### ISSUE TITLE
can't Insert or Update for mssql datatype of time(0)

### ISSUE THREAD

**Issue by jackswei** [MoonStorm/Dapper.FastCRUD#89]
i use dapper is ok,but use Dapper.FastCRUD can't Insert or Update for mssql datatype of time(0)

**Comment by MoonStorm** [comment]
Could you post a sample?

**Comment by jackswei** [comment]
i use this model
    [Table("TTRIPowerStatic")]
    public class TTRIPowerStatic
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }

        public DateTime StaticDay { get; set; }

        public TimeSpan STDataTime { get; set; }

        public TimeSpan EDDataTime { get; set; }
        public double Degree { get; set; }
    }
insert 
 TTRIPowerStatic = new TTRIPowerStatic();
                        TTRIPowerStatic.StaticDay = DateTime.Now;
                        TTRIPowerStatic.STDataTime = DateTime.Now.TimeOfDay;

                                TTRIPowerStatic.EDDataTime = DateTime.Now.TimeOfDay;
                                _connectionDB.Insert(TTRIPowerStatic);

**Comment by 0xorial** [comment]
I had similar problem, but with reading - the property was not filled, and I could not use it in WHERE query. It seems that FastCRUD does not recognize TimeSpan type. When I added my own convention which where I overloaded IsSimpleSqlType method, it started working.

**Comment by FruitAndAShape** [comment]
Hear, hear... this doesn't work.
