### ISSUE TITLE
did fastcrud  lock db table?

### ISSUE THREAD

**Issue by wuzhenda** [MoonStorm/Dapper.FastCRUD#90]
I use fastcrud to manage  sql server which already used by another project .
When  use the "Find" method to get certain data from a db table, I always get the following error,which I googled,as I may locked a table which the another project is needed,and the another project did the same thing. as I just use one db table why I need antoher table that locked by another project ?

"transaction (process ID 84) and another process is deadlocked on the lock resource and has been chosen as a deadlock victim. Please rerun the transaction."

**Comment by MoonStorm** [comment]
No, FastCrud isn't using locks. The server does however, depending on the isolation level set.

**Comment by wuzhenda** [comment]
the "Find" method   just read data from sql,why need "transaction" ? I think that make the sql locked table

**Comment by MoonStorm** [comment]
The library isn't using any transactions by default. Google 'isolation level locks'. Even a simple SELECT creates locks.
