### ISSUE TITLE
Discussion: Bulk Inserting

### ISSUE THREAD

**Issue by fir3pho3nixx** [MoonStorm/Dapper.FastCRUD#91]
Hi

We are using your framework for persistence and it is going well so far. The new feature we are developing requires the ability to do bulk inserts. I was just wondering if there was any support for it outside of what I have found in the [docs](https://github.com/MoonStorm/Dapper.FastCRUD/wiki#inserting) for doing this? 

If not are you guys willing to accept contributions for this? I might be totally barking up the wrong tree here, so opinions are most welcome. 

I also know I can do this using Dapper Contrib but I would prefer to stick with one pathway for achieving this. 

Thanks!

**Comment by MoonStorm** [comment]
Of course we accept contributions. Tell us more about the improvements you're planning on adding to the project.

**Comment by fir3pho3nixx** [comment]
I had a quick look at the dapper contrib code and it looks like the API for doing Insert<T> is backed on to the Execute extension which takes advantage of buffering. It is also documented [here](https://github.com/StackExchange/Dapper#execute-a-command-multiple-times). 

If we use this approach, perhaps the heavy lifting has been done already. The only thing I am not sure about is how the database generated id's flow back out into the POCO's.

**Comment by fir3pho3nixx** [comment]
To help the discussion along, I will have a go at doing a spike and add my findings here. Just need to install all the databases to get the tests to pass :)

**Comment by arvand** [comment]
@fir3pho3nixx I tested it and since Dapper will iterate over the collection itself and FastCrud caches the sql statements, there is just a little performance gain if you write a bulk insert method instead of just iterating over the collection and doing an insert.
If your collection is really big you should use a temp table.

**Comment by fir3pho3nixx** [comment]
@arvand I think you right you are right about Dapper. I found the relevant source line [here](https://github.com/StackExchange/Dapper/blob/master/Dapper/SqlMapper.cs#L552) that demonstrates it executing in a loop.

Do you think batching insert's would yield a performance gain as there is less chatter over network(ie. One at a time vs 200 at a time). I have also seen this in practice and it does speed things up. The alternative I have also come across is doing SqlBulkCopy(which I believe is the fastest). It would mean that it is a vendor specific thing, which I am not sure how it would fit into FastCRUD just yet.

**Comment by arvand** [comment]
@fir3pho3nixx  please have a look at this link https://stackoverflow.com/questions/10689779/bulk-inserts-taking-longer-than-expected-using-dapper 
SqlBulkCopy is the fastest way, I think there was a (not free) plugin called Dapper Plus which used bulk copy.

**Comment by fir3pho3nixx** [comment]
Yes, I remember ayende blogging about the performance degradation of declaring explicit transactions vs not having them at all. Declaring a transaction wins every time, well at least with the right level of propagation and isolation. If memory serves this is because SQL Server will declare implicit transactions for each statement independently outside the scope of a parent transaction. We are using TransactionScope. 

@arvand, @MoonStorm 

- Are we saying this is not the framework for that kind of feature? If so, no problem at all. However should we update the docs with a section reminding people of the learnings here? Until @arvand reminded me, I forgot that transactions was a thing. 

- Or are we saying yip happy to continue however SqlServer is not the only thing we do, it needs to be a considered approach for the rest of the vendor db's we support?

**Comment by arvand** [comment]
Why shouldn't it be a framework for this kind of feature? there is already an extension on Dapper that does bulk insert/update/merge, so I think it is worth the effort.
And I think you should either use bulkCopy or just generate the strings and concat them (as a simple solution), don't know.

**Comment by fir3pho3nixx** [comment]
Hi guys clearing out my backlog and won't have time to work on this. Hope that is OK.

**Comment by AqlaSolutions** [comment]
+1
You have bulk-everything but not bulk insert? What is going on in this world! Dapper.Contrib doesn't support column name mapping, DapperExtensions is 3 years old. No good options.
