### ISSUE TITLE
Insert an entity with related entities

### ISSUE THREAD

**Issue by arvand** [MoonStorm/Dapper.FastCRUD#92]
@MoonStorm  Can I insert an entity with related entities using FastCrud? If yes how many levels of nested children does it support?

**Comment by arvand** [comment]
So for solving this problem I added two methods to OrmConfiguration, one that returns the foreign column name of the child entity (which internally uses _FindRelationship_)  and another method to return the Identity column name of the parent:

```
var identityColumnName = OrmConfiguration.GetEntityIdentifier<parentEntity>();
var foreignColumnName = OrmConfiguration.GetParentChildRelatedColumnName<parentEntity, childEntity>();
```
and by using these two methods and using FastMember (it's better than reflection) I could write a method to Insert the parent and child entities. (First I insert the parent get the identity value and set that value to child's foreign property column by using FastMemeber)

@MoonStorm Could you please share your thoughts about this solution?
I also wanted to thank you for your library which is really great, I am writing a blog about it and want publish a sample to use repositories+Unit of work with FastCrud. 

p.s: I think if OrmConfiguration exposed a method like "GetEntityMapping" for reading the configurations like GetTableName, GetChildParentRelationship, that would have been a better than my way.

**Comment by MoonStorm** [comment]
In my opinion this is way outside the scope of this library. It's getting too close to a full blown ORM and soon enough people are gonna start asking about entity proxies, change detection and whatnot.

**Comment by arvand** [comment]
In our case, we are using it for web application and I think in most of the scenarios for web applications you usually want to update/insert an entity with its relation ( i.e you have grid and the user inputs some data).
So I think you give this functionality to the developer and it will very useful for web applications and since your library is really great, you can give this feature by just few lines of code.   (You can even generate the SQL instead of using FastMember and it will even further enhance the performance)

**Comment by MoonStorm** [comment]
Wouldn't you need go down the chain of related entities, check their ids to see whether you need to insert or update them, then you'd have to somehow detect whether updates are indeed required for each child?

**Comment by arvand** [comment]
Usually no, because in web applications you usually show some data to the user in a grid or some other component, the user selects some data for editing or inserts some new rows. So when you get the data in the server you know which entity needs to get updated and which needs to be inserted.

**Comment by MoonStorm** [comment]
I still think it's a slippery slope. And the operation can't be guaranteed to be atomic. It's best to let people do their insert or update of child entities manually inside their own transaction.
