### ISSUE TITLE
one to one releationship

### ISSUE THREAD

**Issue by generik0** [MoonStorm/Dapper.FastCRUD#93]
Hi

If i have an entiry with 1 to 1 relationship it does not seam to map with include.
If i make it one to many (by just adding IEnumerable) i get the records from the join.

Should 1:1 not use include? if not id there anything else that can be done?

<pre><code>

Works:
public class Enterprise : IEntity<int>
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public IEnumerable<Contact> Contacts { get; set; }
}

\\Does not work:
<pre><code>
public class Enterprise : IEntity<int>
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public Contact Contact { get; set; }
}
</code></pre>

BR Rik

**Comment by generik0** [comment]
OK, OK  if i have the ForeignKey in the Enterprise  for the Contact it will do the one to one. Its just a bit weird as it is contact that is the "Child" of the Parent "Enterprise" so only Contract know the Enterprise id. And the Contact entity does have the ForeignKey attribute on EnterpriseId.

Is there an issue that fastcrud does not:

`Left Join Contract on Enterprise.Id on Contract.EnterpriseId` when there is no ForeignKey  in Enterprise.
If not, shouldn't it?

`public class Contact : IEntity<int>
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Role { get; set; }
        [ForeignKey(nameof(Enterprise))]
        public int EnterpriseId { get; set; }
        public Enterprise Enterprise { get; set; }
    }
`

**Comment by generik0** [comment]
Anyone? Any ideas to get the mapping to understand the 1:1 relationship from the "parent" entity that doesn't have a FK?

**Comment by MoonStorm** [comment]
No, I don't believe it works without the attributes.

**Comment by generik0** [comment]
But there is attributes. On the "child" relation class / entity.
Why does the mapper need a relationship on both sides? If there is a ForeignKey in one entity any a property in the other (parent) entity the mapper could "just" deduct a 1:1 releationship?

**Comment by MoonStorm** [comment]
In theory you're right, it shouldn't need an attribute on the other side. The docs also specify this. But from your experience it seems that the code expects an ``IEnumerable`` on the other side?

**Comment by MoonStorm** [comment]
One-to-one is now supported in v3.0. The wiki has been updated with the details.
