### ISSUE TITLE
Question: Mark property as Foreign Key

### ISSUE THREAD

**Issue by arvand** [MoonStorm/Dapper.FastCRUD#94]
How can I mark a property as ForeignKey with fluent registration?

**Comment by generik0** [comment]
[ForeignKey(nameof(Enterprise))]
        public int EnterpriseId { get; set; }
        public Enterprise Enterprise { get; set;}

**Comment by generik0** [comment]
It's in the system dataanotations schema namespace

**Comment by arvand** [comment]
@generik0 I wanted to do that with "fluent registration", any idea?

**Comment by generik0** [comment]
Well if you ask me, even though it isn't POCO then the attributes on the entity are fluent registration.
But you want to do it with the global static ormmapper calls, right?
Sorry cant help you there, i havnet looked info it enough...

**Comment by arvand** [comment]
well it was in the documents and I missed it:
   OrmConfiguration.GetDefaultEntityMapping<Building>()
      .SetProperty(building => building.OwnerId, 
         prop => prop.SetChildParentRelationship<Owner>("Owner"));
