### ISSUE TITLE
Join more than two entites

### ISSUE THREAD

**Issue by arvand** [MoonStorm/Dapper.FastCRUD#95]
Is there any way I can join more than two entities? 
p.s: Since ConstructFullJoinSelectStatement is looping through the entities I think with some modifications it can support it but I'm not sure how right now. 

@MoonStorm Can you give me hint or any idea to fix this since I don't comprehend your code fully yet.

**Comment by MoonStorm** [comment]
Of course you can. I found this while searching through the code, in the tests: `_testContext.DatabaseConnection.Find<Building>(options => options.Include<Workstation>()             .Include<Employee>())`

**Comment by Thowk** [comment]
I have simmilar problem. @MoonStorm Could you take a look at question on StackOverflow?
https://stackoverflow.com/questions/46114649/how-to-configure-dapper-fastcrud-foreignkey-relation

**Comment by MoonStorm** [comment]
Hmm, I'm not 100% sure, but I believe in those cases you should be able to add the attribute on the property holding the foreign entity?

**Comment by Thowk** [comment]
If you meant something like this:

    public class Code
    {
        [Key]
        public int CodeId { get; set; }

        [ForeignKey(nameof(CodeId))]
        public Label LabelData { get; set; }

        [ForeignKey(nameof(CodeId))]
        public Prop PropData { get; set; }
    }

It didn't work either. Same error as I mentioned in post.
