### ISSUE TITLE
Dapper.FastCrud.ModelGenerator  Issues with foreign keys not generated

### ISSUE THREAD

**Issue by georgepikoulas** [MoonStorm/Dapper.FastCRUD#96]
Hello MoonStorm ,first of all I want to thank you for creating such as amazin library for much easier usage of Dapper in our projects.
I am having issues with the Dapper.FastCrud.ModelGenerator  who correctly created the /Models folder and generated the table for my DB however there are no foreign key relations in teh partial classe at all.
And for just testing out I tried to generte the model using EF Code first from an existing DB and it recogniosed all the proper foreign keys.

Do you have any recommendations on this.

**Comment by MoonStorm** [comment]
You're gonna have to debug the T4 template and see why it's not picking up the relationships.

**Comment by kipusoep** [comment]
Having the same issue, I altered my T4 template to skip those fields and add them via partial classes, including navigation properties.

**Comment by 0xorial** [comment]
I had same issue, but then I found IncludeRelationships flag. Are you sure you are setting it to true?

**Comment by kipusoep** [comment]
Thanks @0xorial, didn't set this flag to true :-)
