### ISSUE TITLE
Select with nolock

### ISSUE THREAD

**Issue by MNie** [MoonStorm/Dapper.FastCRUD#97]
I'm curious if there is a possibility to generate a query with `with(updlock, rowlock)` information.

I have a raw sql like that:

```
$@" SELECT top 1 * FROM {nameof(Table1)} deq with(updlock,rowlock)
                    WHERE {nameof(Table1.Column3)} = 0 or {nameof(Table1.Column3)} = 2
                    ORDER BY {nameof(Table1.Column1)}, {nameof(Table1.Column2)}
            "
```

and a query generated by FastCrud:

```
_dbConnection.Find<Table1>(x => x
                    .Where($"{nameof(Table1.Column3)} = 0 or {nameof(Table1.Column3)} = 2")
                    .OrderBy($"{nameof(Table1.Column1)}, {nameof(Table1.Column2)}")
                    .Top(1)
                    .AttachToTransaction(tx)
                )
                .FirstOrDefault();
```

But I don't know how to add to the query generated by FastCrud a `with(updlock, rowlock)`. I saw a `WithParameters` function but it replaces strings tagged as `@something`

**Comment by MoonStorm** [comment]
We don't have lock hints in the library. You could use the SQL builder that's built into the library to manually create that query.

**Comment by MNie** [comment]
@MoonStorm I create query right now like this. But I have a problem in unit specs where I use SqlLite, So I get an error near `top` and `with(updlock,rowlock)` so I have to deal with it in some `dirty` way. Anyway thanks for an answer :)
